// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/user/user_login_log/user_login_log.proto

package user_login_log

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserLoginLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId   int64  `protobuf:"varint,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginTime string `protobuf:"bytes,3,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	LoginIp   string `protobuf:"bytes,4,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`
	LoginType int64  `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
}

func (x *UserLoginLog) Reset() {
	*x = UserLoginLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginLog) ProtoMessage() {}

func (x *UserLoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginLog.ProtoReflect.Descriptor instead.
func (*UserLoginLog) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginLog) GetLoginId() int64 {
	if x != nil {
		return x.LoginId
	}
	return 0
}

func (x *UserLoginLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoginLog) GetLoginTime() string {
	if x != nil {
		return x.LoginTime
	}
	return ""
}

func (x *UserLoginLog) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *UserLoginLog) GetLoginType() int64 {
	if x != nil {
		return x.LoginType
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type In_GetUserLoginLogInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId int64 `protobuf:"varint,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
}

func (x *In_GetUserLoginLogInfoById) Reset() {
	*x = In_GetUserLoginLogInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserLoginLogInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserLoginLogInfoById) ProtoMessage() {}

func (x *In_GetUserLoginLogInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserLoginLogInfoById.ProtoReflect.Descriptor instead.
func (*In_GetUserLoginLogInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{2}
}

func (x *In_GetUserLoginLogInfoById) GetLoginId() int64 {
	if x != nil {
		return x.LoginId
	}
	return 0
}

type Out_GetUserLoginLogInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
}

func (x *Out_GetUserLoginLogInfoById) Reset() {
	*x = Out_GetUserLoginLogInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserLoginLogInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserLoginLogInfoById) ProtoMessage() {}

func (x *Out_GetUserLoginLogInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserLoginLogInfoById.ProtoReflect.Descriptor instead.
func (*Out_GetUserLoginLogInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{3}
}

func (x *Out_GetUserLoginLogInfoById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserLoginLogInfoById) GetUserLoginLog() *UserLoginLog {
	if x != nil {
		return x.UserLoginLog
	}
	return nil
}

type Out_UpdateUserLoginLogInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
}

func (x *Out_UpdateUserLoginLogInfo) Reset() {
	*x = Out_UpdateUserLoginLogInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateUserLoginLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateUserLoginLogInfo) ProtoMessage() {}

func (x *Out_UpdateUserLoginLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateUserLoginLogInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateUserLoginLogInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{4}
}

func (x *Out_UpdateUserLoginLogInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateUserLoginLogInfo) GetUserLoginLog() *UserLoginLog {
	if x != nil {
		return x.UserLoginLog
	}
	return nil
}

type In_UpdateUserLoginLogInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLoginLog *UserLoginLog `protobuf:"bytes,1,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
}

func (x *In_UpdateUserLoginLogInfo) Reset() {
	*x = In_UpdateUserLoginLogInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateUserLoginLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateUserLoginLogInfo) ProtoMessage() {}

func (x *In_UpdateUserLoginLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateUserLoginLogInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateUserLoginLogInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{5}
}

func (x *In_UpdateUserLoginLogInfo) GetUserLoginLog() *UserLoginLog {
	if x != nil {
		return x.UserLoginLog
	}
	return nil
}

type In_GetUserLoginLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetUserLoginLogs) Reset() {
	*x = In_GetUserLoginLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserLoginLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserLoginLogs) ProtoMessage() {}

func (x *In_GetUserLoginLogs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserLoginLogs.ProtoReflect.Descriptor instead.
func (*In_GetUserLoginLogs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{6}
}

func (x *In_GetUserLoginLogs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetUserLoginLogs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetUserLoginLogs) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetUserLoginLogs) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetUserLoginLogs) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetUserLoginLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error            *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit            int64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages            int64           `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total            int64           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserLoginLogList []*UserLoginLog `protobuf:"bytes,5,rep,name=user_login_log_list,json=userLoginLogList,proto3" json:"user_login_log_list,omitempty"`
}

func (x *Out_GetUserLoginLogs) Reset() {
	*x = Out_GetUserLoginLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserLoginLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserLoginLogs) ProtoMessage() {}

func (x *Out_GetUserLoginLogs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserLoginLogs.ProtoReflect.Descriptor instead.
func (*Out_GetUserLoginLogs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{7}
}

func (x *Out_GetUserLoginLogs) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserLoginLogs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetUserLoginLogs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetUserLoginLogs) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetUserLoginLogs) GetUserLoginLogList() []*UserLoginLog {
	if x != nil {
		return x.UserLoginLogList
	}
	return nil
}

type In_DeleteUserLoginLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLoginLogList []int64 `protobuf:"varint,1,rep,packed,name=user_login_log_list,json=userLoginLogList,proto3" json:"user_login_log_list,omitempty"`
}

func (x *In_DeleteUserLoginLogs) Reset() {
	*x = In_DeleteUserLoginLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteUserLoginLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteUserLoginLogs) ProtoMessage() {}

func (x *In_DeleteUserLoginLogs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteUserLoginLogs.ProtoReflect.Descriptor instead.
func (*In_DeleteUserLoginLogs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{8}
}

func (x *In_DeleteUserLoginLogs) GetUserLoginLogList() []int64 {
	if x != nil {
		return x.UserLoginLogList
	}
	return nil
}

type Out_DeleteUserLoginLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteUserLoginLogs) Reset() {
	*x = Out_DeleteUserLoginLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteUserLoginLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteUserLoginLogs) ProtoMessage() {}

func (x *Out_DeleteUserLoginLogs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteUserLoginLogs.ProtoReflect.Descriptor instead.
func (*Out_DeleteUserLoginLogs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{9}
}

func (x *Out_DeleteUserLoginLogs) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateUserLoginLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLoginLog *UserLoginLog `protobuf:"bytes,1,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
}

func (x *In_CreateUserLoginLog) Reset() {
	*x = In_CreateUserLoginLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateUserLoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateUserLoginLog) ProtoMessage() {}

func (x *In_CreateUserLoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateUserLoginLog.ProtoReflect.Descriptor instead.
func (*In_CreateUserLoginLog) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{10}
}

func (x *In_CreateUserLoginLog) GetUserLoginLog() *UserLoginLog {
	if x != nil {
		return x.UserLoginLog
	}
	return nil
}

type Out_CreateUserLoginLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
}

func (x *Out_CreateUserLoginLog) Reset() {
	*x = Out_CreateUserLoginLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateUserLoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateUserLoginLog) ProtoMessage() {}

func (x *Out_CreateUserLoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_login_log_user_login_log_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateUserLoginLog.ProtoReflect.Descriptor instead.
func (*Out_CreateUserLoginLog) Descriptor() ([]byte, []int) {
	return file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP(), []int{11}
}

func (x *Out_CreateUserLoginLog) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateUserLoginLog) GetUserLoginLog() *UserLoginLog {
	if x != nil {
		return x.UserLoginLog
	}
	return nil
}

var File_modules_user_user_login_log_user_login_log_proto protoreflect.FileDescriptor

var file_modules_user_user_login_log_user_login_log_proto_rawDesc = []byte{
	0x0a, 0x30, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x67, 0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x1a, 0x49, 0x6e, 0x5f,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x1b, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x44, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x22, 0x8f, 0x01, 0x0a, 0x1a, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x44, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x22, 0x61, 0x0a, 0x19, 0x49, 0x6e, 0x5f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x22, 0x9a, 0x01, 0x0a, 0x13, 0x49,
	0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f,
	0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x14, 0x4f, 0x75, 0x74, 0x5f,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73,
	0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x4d, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f,
	0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x10, 0x75, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x47,
	0x0a, 0x16, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x2d, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x17, 0x4f, 0x75, 0x74, 0x5f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f,
	0x67, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x5d, 0x0a, 0x15, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x12, 0x44, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67,
	0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x22, 0x8b,
	0x01, 0x0a, 0x16, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x44, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0c,
	0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x32, 0xb0, 0x04, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x74, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x2a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x2b, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74,
	0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x16, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x2a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x5f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x1a, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x22, 0x00, 0x12, 0x68,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x1a, 0x27, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f,
	0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x12, 0x25,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x22, 0x00, 0x42,
	0x50, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x69, 0x61, 0x6e, 0x78, 0x75, 0x6e, 0x6b, 0x65,
	0x2e, 0x65, 0x67, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x01, 0x5a, 0x1a, 0x67, 0x6f,
	0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0xa2, 0x02, 0x06, 0x55, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_user_user_login_log_user_login_log_proto_rawDescOnce sync.Once
	file_modules_user_user_login_log_user_login_log_proto_rawDescData = file_modules_user_user_login_log_user_login_log_proto_rawDesc
)

func file_modules_user_user_login_log_user_login_log_proto_rawDescGZIP() []byte {
	file_modules_user_user_login_log_user_login_log_proto_rawDescOnce.Do(func() {
		file_modules_user_user_login_log_user_login_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_user_user_login_log_user_login_log_proto_rawDescData)
	})
	return file_modules_user_user_login_log_user_login_log_proto_rawDescData
}

var file_modules_user_user_login_log_user_login_log_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_modules_user_user_login_log_user_login_log_proto_goTypes = []interface{}{
	(*UserLoginLog)(nil),                // 0: user_login_log.User_login_log
	(*Error)(nil),                       // 1: user_login_log.Error
	(*In_GetUserLoginLogInfoById)(nil),  // 2: user_login_log.In_GetUserLoginLogInfoById
	(*Out_GetUserLoginLogInfoById)(nil), // 3: user_login_log.Out_GetUserLoginLogInfoById
	(*Out_UpdateUserLoginLogInfo)(nil),  // 4: user_login_log.Out_UpdateUserLoginLogInfo
	(*In_UpdateUserLoginLogInfo)(nil),   // 5: user_login_log.In_UpdateUserLoginLogInfo
	(*In_GetUserLoginLogs)(nil),         // 6: user_login_log.In_GetUserLoginLogs
	(*Out_GetUserLoginLogs)(nil),        // 7: user_login_log.Out_GetUserLoginLogs
	(*In_DeleteUserLoginLogs)(nil),      // 8: user_login_log.In_DeleteUserLoginLogs
	(*Out_DeleteUserLoginLogs)(nil),     // 9: user_login_log.Out_DeleteUserLoginLogs
	(*In_CreateUserLoginLog)(nil),       // 10: user_login_log.In_CreateUserLoginLog
	(*Out_CreateUserLoginLog)(nil),      // 11: user_login_log.Out_CreateUserLoginLog
}
var file_modules_user_user_login_log_user_login_log_proto_depIdxs = []int32{
	1,  // 0: user_login_log.Out_GetUserLoginLogInfoById.error:type_name -> user_login_log.Error
	0,  // 1: user_login_log.Out_GetUserLoginLogInfoById.user_login_log:type_name -> user_login_log.User_login_log
	1,  // 2: user_login_log.Out_UpdateUserLoginLogInfo.error:type_name -> user_login_log.Error
	0,  // 3: user_login_log.Out_UpdateUserLoginLogInfo.user_login_log:type_name -> user_login_log.User_login_log
	0,  // 4: user_login_log.In_UpdateUserLoginLogInfo.user_login_log:type_name -> user_login_log.User_login_log
	1,  // 5: user_login_log.Out_GetUserLoginLogs.error:type_name -> user_login_log.Error
	0,  // 6: user_login_log.Out_GetUserLoginLogs.user_login_log_list:type_name -> user_login_log.User_login_log
	1,  // 7: user_login_log.Out_DeleteUserLoginLogs.error:type_name -> user_login_log.Error
	0,  // 8: user_login_log.In_CreateUserLoginLog.user_login_log:type_name -> user_login_log.User_login_log
	1,  // 9: user_login_log.Out_CreateUserLoginLog.error:type_name -> user_login_log.Error
	0,  // 10: user_login_log.Out_CreateUserLoginLog.user_login_log:type_name -> user_login_log.User_login_log
	2,  // 11: user_login_log.UserLoginLogService.GetUserLoginLogInfoById:input_type -> user_login_log.In_GetUserLoginLogInfoById
	5,  // 12: user_login_log.UserLoginLogService.UpdateUserLoginLogInfo:input_type -> user_login_log.In_UpdateUserLoginLogInfo
	6,  // 13: user_login_log.UserLoginLogService.GetUserLoginLogs:input_type -> user_login_log.In_GetUserLoginLogs
	8,  // 14: user_login_log.UserLoginLogService.DeleteUserLoginLogs:input_type -> user_login_log.In_DeleteUserLoginLogs
	10, // 15: user_login_log.UserLoginLogService.CreateUserLoginLog:input_type -> user_login_log.In_CreateUserLoginLog
	3,  // 16: user_login_log.UserLoginLogService.GetUserLoginLogInfoById:output_type -> user_login_log.Out_GetUserLoginLogInfoById
	4,  // 17: user_login_log.UserLoginLogService.UpdateUserLoginLogInfo:output_type -> user_login_log.Out_UpdateUserLoginLogInfo
	7,  // 18: user_login_log.UserLoginLogService.GetUserLoginLogs:output_type -> user_login_log.Out_GetUserLoginLogs
	9,  // 19: user_login_log.UserLoginLogService.DeleteUserLoginLogs:output_type -> user_login_log.Out_DeleteUserLoginLogs
	11, // 20: user_login_log.UserLoginLogService.CreateUserLoginLog:output_type -> user_login_log.Out_CreateUserLoginLog
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_modules_user_user_login_log_user_login_log_proto_init() }
func file_modules_user_user_login_log_user_login_log_proto_init() {
	if File_modules_user_user_login_log_user_login_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserLoginLogInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserLoginLogInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateUserLoginLogInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateUserLoginLogInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserLoginLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserLoginLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteUserLoginLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteUserLoginLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateUserLoginLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_login_log_user_login_log_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateUserLoginLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_user_user_login_log_user_login_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_user_user_login_log_user_login_log_proto_goTypes,
		DependencyIndexes: file_modules_user_user_login_log_user_login_log_proto_depIdxs,
		MessageInfos:      file_modules_user_user_login_log_user_login_log_proto_msgTypes,
	}.Build()
	File_modules_user_user_login_log_user_login_log_proto = out.File
	file_modules_user_user_login_log_user_login_log_proto_rawDesc = nil
	file_modules_user_user_login_log_user_login_log_proto_goTypes = nil
	file_modules_user_user_login_log_user_login_log_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserLoginLogServiceClient is the client API for UserLoginLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserLoginLogServiceClient interface {
	//获取信息
	GetUserLoginLogInfoById(ctx context.Context, in *In_GetUserLoginLogInfoById, opts ...grpc.CallOption) (*Out_GetUserLoginLogInfoById, error)
	//修改信息
	UpdateUserLoginLogInfo(ctx context.Context, in *In_UpdateUserLoginLogInfo, opts ...grpc.CallOption) (*Out_UpdateUserLoginLogInfo, error)
	//获取列表
	GetUserLoginLogs(ctx context.Context, in *In_GetUserLoginLogs, opts ...grpc.CallOption) (*Out_GetUserLoginLogs, error)
	//删除列表
	DeleteUserLoginLogs(ctx context.Context, in *In_DeleteUserLoginLogs, opts ...grpc.CallOption) (*Out_DeleteUserLoginLogs, error)
	//新建信息
	CreateUserLoginLog(ctx context.Context, in *In_CreateUserLoginLog, opts ...grpc.CallOption) (*Out_CreateUserLoginLog, error)
}

type userLoginLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserLoginLogServiceClient(cc grpc.ClientConnInterface) UserLoginLogServiceClient {
	return &userLoginLogServiceClient{cc}
}

func (c *userLoginLogServiceClient) GetUserLoginLogInfoById(ctx context.Context, in *In_GetUserLoginLogInfoById, opts ...grpc.CallOption) (*Out_GetUserLoginLogInfoById, error) {
	out := new(Out_GetUserLoginLogInfoById)
	err := c.cc.Invoke(ctx, "/user_login_log.UserLoginLogService/GetUserLoginLogInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLoginLogServiceClient) UpdateUserLoginLogInfo(ctx context.Context, in *In_UpdateUserLoginLogInfo, opts ...grpc.CallOption) (*Out_UpdateUserLoginLogInfo, error) {
	out := new(Out_UpdateUserLoginLogInfo)
	err := c.cc.Invoke(ctx, "/user_login_log.UserLoginLogService/UpdateUserLoginLogInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLoginLogServiceClient) GetUserLoginLogs(ctx context.Context, in *In_GetUserLoginLogs, opts ...grpc.CallOption) (*Out_GetUserLoginLogs, error) {
	out := new(Out_GetUserLoginLogs)
	err := c.cc.Invoke(ctx, "/user_login_log.UserLoginLogService/GetUserLoginLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLoginLogServiceClient) DeleteUserLoginLogs(ctx context.Context, in *In_DeleteUserLoginLogs, opts ...grpc.CallOption) (*Out_DeleteUserLoginLogs, error) {
	out := new(Out_DeleteUserLoginLogs)
	err := c.cc.Invoke(ctx, "/user_login_log.UserLoginLogService/DeleteUserLoginLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLoginLogServiceClient) CreateUserLoginLog(ctx context.Context, in *In_CreateUserLoginLog, opts ...grpc.CallOption) (*Out_CreateUserLoginLog, error) {
	out := new(Out_CreateUserLoginLog)
	err := c.cc.Invoke(ctx, "/user_login_log.UserLoginLogService/CreateUserLoginLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLoginLogServiceServer is the server API for UserLoginLogService service.
type UserLoginLogServiceServer interface {
	//获取信息
	GetUserLoginLogInfoById(context.Context, *In_GetUserLoginLogInfoById) (*Out_GetUserLoginLogInfoById, error)
	//修改信息
	UpdateUserLoginLogInfo(context.Context, *In_UpdateUserLoginLogInfo) (*Out_UpdateUserLoginLogInfo, error)
	//获取列表
	GetUserLoginLogs(context.Context, *In_GetUserLoginLogs) (*Out_GetUserLoginLogs, error)
	//删除列表
	DeleteUserLoginLogs(context.Context, *In_DeleteUserLoginLogs) (*Out_DeleteUserLoginLogs, error)
	//新建信息
	CreateUserLoginLog(context.Context, *In_CreateUserLoginLog) (*Out_CreateUserLoginLog, error)
}

// UnimplementedUserLoginLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserLoginLogServiceServer struct {
}

func (*UnimplementedUserLoginLogServiceServer) GetUserLoginLogInfoById(context.Context, *In_GetUserLoginLogInfoById) (*Out_GetUserLoginLogInfoById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLoginLogInfoById not implemented")
}
func (*UnimplementedUserLoginLogServiceServer) UpdateUserLoginLogInfo(context.Context, *In_UpdateUserLoginLogInfo) (*Out_UpdateUserLoginLogInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserLoginLogInfo not implemented")
}
func (*UnimplementedUserLoginLogServiceServer) GetUserLoginLogs(context.Context, *In_GetUserLoginLogs) (*Out_GetUserLoginLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLoginLogs not implemented")
}
func (*UnimplementedUserLoginLogServiceServer) DeleteUserLoginLogs(context.Context, *In_DeleteUserLoginLogs) (*Out_DeleteUserLoginLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserLoginLogs not implemented")
}
func (*UnimplementedUserLoginLogServiceServer) CreateUserLoginLog(context.Context, *In_CreateUserLoginLog) (*Out_CreateUserLoginLog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserLoginLog not implemented")
}

func RegisterUserLoginLogServiceServer(s *grpc.Server, srv UserLoginLogServiceServer) {
	s.RegisterService(&_UserLoginLogService_serviceDesc, srv)
}

func _UserLoginLogService_GetUserLoginLogInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserLoginLogInfoById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLoginLogServiceServer).GetUserLoginLogInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_login_log.UserLoginLogService/GetUserLoginLogInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLoginLogServiceServer).GetUserLoginLogInfoById(ctx, req.(*In_GetUserLoginLogInfoById))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLoginLogService_UpdateUserLoginLogInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateUserLoginLogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLoginLogServiceServer).UpdateUserLoginLogInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_login_log.UserLoginLogService/UpdateUserLoginLogInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLoginLogServiceServer).UpdateUserLoginLogInfo(ctx, req.(*In_UpdateUserLoginLogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLoginLogService_GetUserLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserLoginLogs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLoginLogServiceServer).GetUserLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_login_log.UserLoginLogService/GetUserLoginLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLoginLogServiceServer).GetUserLoginLogs(ctx, req.(*In_GetUserLoginLogs))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLoginLogService_DeleteUserLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteUserLoginLogs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLoginLogServiceServer).DeleteUserLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_login_log.UserLoginLogService/DeleteUserLoginLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLoginLogServiceServer).DeleteUserLoginLogs(ctx, req.(*In_DeleteUserLoginLogs))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLoginLogService_CreateUserLoginLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateUserLoginLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLoginLogServiceServer).CreateUserLoginLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_login_log.UserLoginLogService/CreateUserLoginLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLoginLogServiceServer).CreateUserLoginLog(ctx, req.(*In_CreateUserLoginLog))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserLoginLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_login_log.UserLoginLogService",
	HandlerType: (*UserLoginLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserLoginLogInfoById",
			Handler:    _UserLoginLogService_GetUserLoginLogInfoById_Handler,
		},
		{
			MethodName: "UpdateUserLoginLogInfo",
			Handler:    _UserLoginLogService_UpdateUserLoginLogInfo_Handler,
		},
		{
			MethodName: "GetUserLoginLogs",
			Handler:    _UserLoginLogService_GetUserLoginLogs_Handler,
		},
		{
			MethodName: "DeleteUserLoginLogs",
			Handler:    _UserLoginLogService_DeleteUserLoginLogs_Handler,
		},
		{
			MethodName: "CreateUserLoginLog",
			Handler:    _UserLoginLogService_CreateUserLoginLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/user/user_login_log/user_login_log.proto",
}
