// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/user/user_addr/user_addr.proto

package user_addr

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddrId   int64  `protobuf:"varint,1,opt,name=user_addr_id,json=userAddrId,proto3" json:"user_addr_id,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Zip          int64  `protobuf:"varint,3,opt,name=zip,proto3" json:"zip,omitempty"`
	Province     string `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City         string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District     string `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	Address      string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	IsDefault    int64  `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	ModifiedTime string `protobuf:"bytes,9,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
}

func (x *UserAddr) Reset() {
	*x = UserAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddr) ProtoMessage() {}

func (x *UserAddr) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddr.ProtoReflect.Descriptor instead.
func (*UserAddr) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{1}
}

func (x *UserAddr) GetUserAddrId() int64 {
	if x != nil {
		return x.UserAddrId
	}
	return 0
}

func (x *UserAddr) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAddr) GetZip() int64 {
	if x != nil {
		return x.Zip
	}
	return 0
}

func (x *UserAddr) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserAddr) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserAddr) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserAddr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserAddr) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UserAddr) GetModifiedTime() string {
	if x != nil {
		return x.ModifiedTime
	}
	return ""
}

type In_GetUserAddrInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddrId int64 `protobuf:"varint,1,opt,name=user_addr_id,json=userAddrId,proto3" json:"user_addr_id,omitempty"`
}

func (x *In_GetUserAddrInfoById) Reset() {
	*x = In_GetUserAddrInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserAddrInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserAddrInfoById) ProtoMessage() {}

func (x *In_GetUserAddrInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserAddrInfoById.ProtoReflect.Descriptor instead.
func (*In_GetUserAddrInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{2}
}

func (x *In_GetUserAddrInfoById) GetUserAddrId() int64 {
	if x != nil {
		return x.UserAddrId
	}
	return 0
}

type Out_GetUserAddrInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
}

func (x *Out_GetUserAddrInfoById) Reset() {
	*x = Out_GetUserAddrInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserAddrInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserAddrInfoById) ProtoMessage() {}

func (x *Out_GetUserAddrInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserAddrInfoById.ProtoReflect.Descriptor instead.
func (*Out_GetUserAddrInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{3}
}

func (x *Out_GetUserAddrInfoById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserAddrInfoById) GetUserAddr() *UserAddr {
	if x != nil {
		return x.UserAddr
	}
	return nil
}

type Out_UpdateUserAddrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
}

func (x *Out_UpdateUserAddrInfo) Reset() {
	*x = Out_UpdateUserAddrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateUserAddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateUserAddrInfo) ProtoMessage() {}

func (x *Out_UpdateUserAddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateUserAddrInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateUserAddrInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{4}
}

func (x *Out_UpdateUserAddrInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateUserAddrInfo) GetUserAddr() *UserAddr {
	if x != nil {
		return x.UserAddr
	}
	return nil
}

type In_UpdateUserAddrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddr *UserAddr `protobuf:"bytes,1,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
}

func (x *In_UpdateUserAddrInfo) Reset() {
	*x = In_UpdateUserAddrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateUserAddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateUserAddrInfo) ProtoMessage() {}

func (x *In_UpdateUserAddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateUserAddrInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateUserAddrInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{5}
}

func (x *In_UpdateUserAddrInfo) GetUserAddr() *UserAddr {
	if x != nil {
		return x.UserAddr
	}
	return nil
}

type In_GetUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetUserAddrs) Reset() {
	*x = In_GetUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserAddrs) ProtoMessage() {}

func (x *In_GetUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserAddrs.ProtoReflect.Descriptor instead.
func (*In_GetUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{6}
}

func (x *In_GetUserAddrs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetUserAddrs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetUserAddrs) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetUserAddrs) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetUserAddrs) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit        int64       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages        int64       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total        int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserAddrList []*UserAddr `protobuf:"bytes,5,rep,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
}

func (x *Out_GetUserAddrs) Reset() {
	*x = Out_GetUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserAddrs) ProtoMessage() {}

func (x *Out_GetUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserAddrs.ProtoReflect.Descriptor instead.
func (*Out_GetUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{7}
}

func (x *Out_GetUserAddrs) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserAddrs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetUserAddrs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetUserAddrs) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetUserAddrs) GetUserAddrList() []*UserAddr {
	if x != nil {
		return x.UserAddrList
	}
	return nil
}

type In_DeleteUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddrList []int64 `protobuf:"varint,1,rep,packed,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
}

func (x *In_DeleteUserAddrs) Reset() {
	*x = In_DeleteUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteUserAddrs) ProtoMessage() {}

func (x *In_DeleteUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteUserAddrs.ProtoReflect.Descriptor instead.
func (*In_DeleteUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{8}
}

func (x *In_DeleteUserAddrs) GetUserAddrList() []int64 {
	if x != nil {
		return x.UserAddrList
	}
	return nil
}

type Out_DeleteUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteUserAddrs) Reset() {
	*x = Out_DeleteUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteUserAddrs) ProtoMessage() {}

func (x *Out_DeleteUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteUserAddrs.ProtoReflect.Descriptor instead.
func (*Out_DeleteUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{9}
}

func (x *Out_DeleteUserAddrs) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateUserAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddr *UserAddr `protobuf:"bytes,1,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
}

func (x *In_CreateUserAddr) Reset() {
	*x = In_CreateUserAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateUserAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateUserAddr) ProtoMessage() {}

func (x *In_CreateUserAddr) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateUserAddr.ProtoReflect.Descriptor instead.
func (*In_CreateUserAddr) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{10}
}

func (x *In_CreateUserAddr) GetUserAddr() *UserAddr {
	if x != nil {
		return x.UserAddr
	}
	return nil
}

type Out_CreateUserAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error    *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
}

func (x *Out_CreateUserAddr) Reset() {
	*x = Out_CreateUserAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateUserAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateUserAddr) ProtoMessage() {}

func (x *Out_CreateUserAddr) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateUserAddr.ProtoReflect.Descriptor instead.
func (*Out_CreateUserAddr) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{11}
}

func (x *Out_CreateUserAddr) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateUserAddr) GetUserAddr() *UserAddr {
	if x != nil {
		return x.UserAddr
	}
	return nil
}

type In_GetOneUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages  int64  `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *In_GetOneUserAddrs) Reset() {
	*x = In_GetOneUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetOneUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetOneUserAddrs) ProtoMessage() {}

func (x *In_GetOneUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetOneUserAddrs.ProtoReflect.Descriptor instead.
func (*In_GetOneUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{12}
}

func (x *In_GetOneUserAddrs) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *In_GetOneUserAddrs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetOneUserAddrs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type Out_GetOneUserAddrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error        *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit        int64       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages        int64       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total        int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserAddrList []*UserAddr `protobuf:"bytes,5,rep,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
}

func (x *Out_GetOneUserAddrs) Reset() {
	*x = Out_GetOneUserAddrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetOneUserAddrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetOneUserAddrs) ProtoMessage() {}

func (x *Out_GetOneUserAddrs) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_addr_user_addr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetOneUserAddrs.ProtoReflect.Descriptor instead.
func (*Out_GetOneUserAddrs) Descriptor() ([]byte, []int) {
	return file_modules_user_user_addr_user_addr_proto_rawDescGZIP(), []int{13}
}

func (x *Out_GetOneUserAddrs) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetOneUserAddrs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetOneUserAddrs) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetOneUserAddrs) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetOneUserAddrs) GetUserAddrList() []*UserAddr {
	if x != nil {
		return x.UserAddrList
	}
	return nil
}

var File_modules_user_user_addr_user_addr_proto protoreflect.FileDescriptor

var file_modules_user_user_addr_user_addr_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x7a, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x7a, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x3a, 0x0a, 0x16, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x17, 0x4f,
	0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x22, 0x73, 0x0a, 0x16, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x4a, 0x0a, 0x15, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x31, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x65,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x10,
	0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73,
	0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x0e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x3d, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x46, 0x0a, 0x11, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x6f, 0x0a, 0x12, 0x4f, 0x75, 0x74,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x59, 0x0a, 0x12, 0x49, 0x6e,
	0x5f, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x26, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x32, 0x92, 0x04, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x21,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49,
	0x64, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x4f, 0x75,
	0x74, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x5f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73,
	0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x4f, 0x75, 0x74,
	0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x22, 0x00, 0x12,
	0x52, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x73, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x49,
	0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x73, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e, 0x4f, 0x75,
	0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x2e, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x2e,
	0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x73, 0x22, 0x00, 0x42, 0x48, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e,
	0x71, 0x69, 0x61, 0x6e, 0x78, 0x75, 0x6e, 0x6b, 0x65, 0x2e, 0x65, 0x67, 0x6f, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x42, 0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x50, 0x01, 0x5a, 0x15, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0xa2, 0x02, 0x05, 0x55, 0x41, 0x44,
	0x44, 0x52, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_user_user_addr_user_addr_proto_rawDescOnce sync.Once
	file_modules_user_user_addr_user_addr_proto_rawDescData = file_modules_user_user_addr_user_addr_proto_rawDesc
)

func file_modules_user_user_addr_user_addr_proto_rawDescGZIP() []byte {
	file_modules_user_user_addr_user_addr_proto_rawDescOnce.Do(func() {
		file_modules_user_user_addr_user_addr_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_user_user_addr_user_addr_proto_rawDescData)
	})
	return file_modules_user_user_addr_user_addr_proto_rawDescData
}

var file_modules_user_user_addr_user_addr_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_modules_user_user_addr_user_addr_proto_goTypes = []interface{}{
	(*Error)(nil),                   // 0: user_addr.Error
	(*UserAddr)(nil),                // 1: user_addr.User_addr
	(*In_GetUserAddrInfoById)(nil),  // 2: user_addr.In_GetUserAddrInfoById
	(*Out_GetUserAddrInfoById)(nil), // 3: user_addr.Out_GetUserAddrInfoById
	(*Out_UpdateUserAddrInfo)(nil),  // 4: user_addr.Out_UpdateUserAddrInfo
	(*In_UpdateUserAddrInfo)(nil),   // 5: user_addr.In_UpdateUserAddrInfo
	(*In_GetUserAddrs)(nil),         // 6: user_addr.In_GetUserAddrs
	(*Out_GetUserAddrs)(nil),        // 7: user_addr.Out_GetUserAddrs
	(*In_DeleteUserAddrs)(nil),      // 8: user_addr.In_DeleteUserAddrs
	(*Out_DeleteUserAddrs)(nil),     // 9: user_addr.Out_DeleteUserAddrs
	(*In_CreateUserAddr)(nil),       // 10: user_addr.In_CreateUserAddr
	(*Out_CreateUserAddr)(nil),      // 11: user_addr.Out_CreateUserAddr
	(*In_GetOneUserAddrs)(nil),      // 12: user_addr.In_GetOneUserAddrs
	(*Out_GetOneUserAddrs)(nil),     // 13: user_addr.Out_GetOneUserAddrs
}
var file_modules_user_user_addr_user_addr_proto_depIdxs = []int32{
	0,  // 0: user_addr.Out_GetUserAddrInfoById.error:type_name -> user_addr.Error
	1,  // 1: user_addr.Out_GetUserAddrInfoById.user_addr:type_name -> user_addr.User_addr
	0,  // 2: user_addr.Out_UpdateUserAddrInfo.error:type_name -> user_addr.Error
	1,  // 3: user_addr.Out_UpdateUserAddrInfo.user_addr:type_name -> user_addr.User_addr
	1,  // 4: user_addr.In_UpdateUserAddrInfo.user_addr:type_name -> user_addr.User_addr
	0,  // 5: user_addr.Out_GetUserAddrs.error:type_name -> user_addr.Error
	1,  // 6: user_addr.Out_GetUserAddrs.user_addr_list:type_name -> user_addr.User_addr
	0,  // 7: user_addr.Out_DeleteUserAddrs.error:type_name -> user_addr.Error
	1,  // 8: user_addr.In_CreateUserAddr.user_addr:type_name -> user_addr.User_addr
	0,  // 9: user_addr.Out_CreateUserAddr.error:type_name -> user_addr.Error
	1,  // 10: user_addr.Out_CreateUserAddr.user_addr:type_name -> user_addr.User_addr
	0,  // 11: user_addr.Out_GetOneUserAddrs.error:type_name -> user_addr.Error
	1,  // 12: user_addr.Out_GetOneUserAddrs.user_addr_list:type_name -> user_addr.User_addr
	2,  // 13: user_addr.UserAddrService.GetUserAddrInfoById:input_type -> user_addr.In_GetUserAddrInfoById
	5,  // 14: user_addr.UserAddrService.UpdateUserAddrInfo:input_type -> user_addr.In_UpdateUserAddrInfo
	6,  // 15: user_addr.UserAddrService.GetUserAddrs:input_type -> user_addr.In_GetUserAddrs
	8,  // 16: user_addr.UserAddrService.DeleteUserAddrs:input_type -> user_addr.In_DeleteUserAddrs
	10, // 17: user_addr.UserAddrService.CreateUserAddr:input_type -> user_addr.In_CreateUserAddr
	12, // 18: user_addr.UserAddrService.GetOneUserAddrs:input_type -> user_addr.In_GetOneUserAddrs
	3,  // 19: user_addr.UserAddrService.GetUserAddrInfoById:output_type -> user_addr.Out_GetUserAddrInfoById
	4,  // 20: user_addr.UserAddrService.UpdateUserAddrInfo:output_type -> user_addr.Out_UpdateUserAddrInfo
	7,  // 21: user_addr.UserAddrService.GetUserAddrs:output_type -> user_addr.Out_GetUserAddrs
	9,  // 22: user_addr.UserAddrService.DeleteUserAddrs:output_type -> user_addr.Out_DeleteUserAddrs
	11, // 23: user_addr.UserAddrService.CreateUserAddr:output_type -> user_addr.Out_CreateUserAddr
	13, // 24: user_addr.UserAddrService.GetOneUserAddrs:output_type -> user_addr.Out_GetOneUserAddrs
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_modules_user_user_addr_user_addr_proto_init() }
func file_modules_user_user_addr_user_addr_proto_init() {
	if File_modules_user_user_addr_user_addr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_user_user_addr_user_addr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserAddrInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserAddrInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateUserAddrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateUserAddrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateUserAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateUserAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetOneUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_addr_user_addr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetOneUserAddrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_user_user_addr_user_addr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_user_user_addr_user_addr_proto_goTypes,
		DependencyIndexes: file_modules_user_user_addr_user_addr_proto_depIdxs,
		MessageInfos:      file_modules_user_user_addr_user_addr_proto_msgTypes,
	}.Build()
	File_modules_user_user_addr_user_addr_proto = out.File
	file_modules_user_user_addr_user_addr_proto_rawDesc = nil
	file_modules_user_user_addr_user_addr_proto_goTypes = nil
	file_modules_user_user_addr_user_addr_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserAddrServiceClient is the client API for UserAddrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAddrServiceClient interface {
	//获取信息
	GetUserAddrInfoById(ctx context.Context, in *In_GetUserAddrInfoById, opts ...grpc.CallOption) (*Out_GetUserAddrInfoById, error)
	//修改信息
	UpdateUserAddrInfo(ctx context.Context, in *In_UpdateUserAddrInfo, opts ...grpc.CallOption) (*Out_UpdateUserAddrInfo, error)
	//获取列表
	GetUserAddrs(ctx context.Context, in *In_GetUserAddrs, opts ...grpc.CallOption) (*Out_GetUserAddrs, error)
	//删除列表
	DeleteUserAddrs(ctx context.Context, in *In_DeleteUserAddrs, opts ...grpc.CallOption) (*Out_DeleteUserAddrs, error)
	//新建信息
	CreateUserAddr(ctx context.Context, in *In_CreateUserAddr, opts ...grpc.CallOption) (*Out_CreateUserAddr, error)
	//获取某人地址列表
	GetOneUserAddrs(ctx context.Context, in *In_GetOneUserAddrs, opts ...grpc.CallOption) (*Out_GetOneUserAddrs, error)
}

type userAddrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAddrServiceClient(cc grpc.ClientConnInterface) UserAddrServiceClient {
	return &userAddrServiceClient{cc}
}

func (c *userAddrServiceClient) GetUserAddrInfoById(ctx context.Context, in *In_GetUserAddrInfoById, opts ...grpc.CallOption) (*Out_GetUserAddrInfoById, error) {
	out := new(Out_GetUserAddrInfoById)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/GetUserAddrInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddrServiceClient) UpdateUserAddrInfo(ctx context.Context, in *In_UpdateUserAddrInfo, opts ...grpc.CallOption) (*Out_UpdateUserAddrInfo, error) {
	out := new(Out_UpdateUserAddrInfo)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/UpdateUserAddrInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddrServiceClient) GetUserAddrs(ctx context.Context, in *In_GetUserAddrs, opts ...grpc.CallOption) (*Out_GetUserAddrs, error) {
	out := new(Out_GetUserAddrs)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/GetUserAddrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddrServiceClient) DeleteUserAddrs(ctx context.Context, in *In_DeleteUserAddrs, opts ...grpc.CallOption) (*Out_DeleteUserAddrs, error) {
	out := new(Out_DeleteUserAddrs)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/DeleteUserAddrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddrServiceClient) CreateUserAddr(ctx context.Context, in *In_CreateUserAddr, opts ...grpc.CallOption) (*Out_CreateUserAddr, error) {
	out := new(Out_CreateUserAddr)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/CreateUserAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddrServiceClient) GetOneUserAddrs(ctx context.Context, in *In_GetOneUserAddrs, opts ...grpc.CallOption) (*Out_GetOneUserAddrs, error) {
	out := new(Out_GetOneUserAddrs)
	err := c.cc.Invoke(ctx, "/user_addr.UserAddrService/GetOneUserAddrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAddrServiceServer is the server API for UserAddrService service.
type UserAddrServiceServer interface {
	//获取信息
	GetUserAddrInfoById(context.Context, *In_GetUserAddrInfoById) (*Out_GetUserAddrInfoById, error)
	//修改信息
	UpdateUserAddrInfo(context.Context, *In_UpdateUserAddrInfo) (*Out_UpdateUserAddrInfo, error)
	//获取列表
	GetUserAddrs(context.Context, *In_GetUserAddrs) (*Out_GetUserAddrs, error)
	//删除列表
	DeleteUserAddrs(context.Context, *In_DeleteUserAddrs) (*Out_DeleteUserAddrs, error)
	//新建信息
	CreateUserAddr(context.Context, *In_CreateUserAddr) (*Out_CreateUserAddr, error)
	//获取某人地址列表
	GetOneUserAddrs(context.Context, *In_GetOneUserAddrs) (*Out_GetOneUserAddrs, error)
}

// UnimplementedUserAddrServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserAddrServiceServer struct {
}

func (*UnimplementedUserAddrServiceServer) GetUserAddrInfoById(context.Context, *In_GetUserAddrInfoById) (*Out_GetUserAddrInfoById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddrInfoById not implemented")
}
func (*UnimplementedUserAddrServiceServer) UpdateUserAddrInfo(context.Context, *In_UpdateUserAddrInfo) (*Out_UpdateUserAddrInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAddrInfo not implemented")
}
func (*UnimplementedUserAddrServiceServer) GetUserAddrs(context.Context, *In_GetUserAddrs) (*Out_GetUserAddrs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddrs not implemented")
}
func (*UnimplementedUserAddrServiceServer) DeleteUserAddrs(context.Context, *In_DeleteUserAddrs) (*Out_DeleteUserAddrs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAddrs not implemented")
}
func (*UnimplementedUserAddrServiceServer) CreateUserAddr(context.Context, *In_CreateUserAddr) (*Out_CreateUserAddr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAddr not implemented")
}
func (*UnimplementedUserAddrServiceServer) GetOneUserAddrs(context.Context, *In_GetOneUserAddrs) (*Out_GetOneUserAddrs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneUserAddrs not implemented")
}

func RegisterUserAddrServiceServer(s *grpc.Server, srv UserAddrServiceServer) {
	s.RegisterService(&_UserAddrService_serviceDesc, srv)
}

func _UserAddrService_GetUserAddrInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserAddrInfoById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).GetUserAddrInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/GetUserAddrInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).GetUserAddrInfoById(ctx, req.(*In_GetUserAddrInfoById))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddrService_UpdateUserAddrInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateUserAddrInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).UpdateUserAddrInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/UpdateUserAddrInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).UpdateUserAddrInfo(ctx, req.(*In_UpdateUserAddrInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddrService_GetUserAddrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserAddrs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).GetUserAddrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/GetUserAddrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).GetUserAddrs(ctx, req.(*In_GetUserAddrs))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddrService_DeleteUserAddrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteUserAddrs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).DeleteUserAddrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/DeleteUserAddrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).DeleteUserAddrs(ctx, req.(*In_DeleteUserAddrs))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddrService_CreateUserAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateUserAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).CreateUserAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/CreateUserAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).CreateUserAddr(ctx, req.(*In_CreateUserAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddrService_GetOneUserAddrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetOneUserAddrs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddrServiceServer).GetOneUserAddrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_addr.UserAddrService/GetOneUserAddrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddrServiceServer).GetOneUserAddrs(ctx, req.(*In_GetOneUserAddrs))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAddrService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_addr.UserAddrService",
	HandlerType: (*UserAddrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAddrInfoById",
			Handler:    _UserAddrService_GetUserAddrInfoById_Handler,
		},
		{
			MethodName: "UpdateUserAddrInfo",
			Handler:    _UserAddrService_UpdateUserAddrInfo_Handler,
		},
		{
			MethodName: "GetUserAddrs",
			Handler:    _UserAddrService_GetUserAddrs_Handler,
		},
		{
			MethodName: "DeleteUserAddrs",
			Handler:    _UserAddrService_DeleteUserAddrs_Handler,
		},
		{
			MethodName: "CreateUserAddr",
			Handler:    _UserAddrService_CreateUserAddr_Handler,
		},
		{
			MethodName: "GetOneUserAddrs",
			Handler:    _UserAddrService_GetOneUserAddrs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/user/user_addr/user_addr.proto",
}
