// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/user/user_balance_log/user_balance_log.proto

package user_balance_log

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserBalanceLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BalanceId  int64   `protobuf:"varint,1,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
	UserId     string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source     int64   `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	SourceSn   int64   `protobuf:"varint,4,opt,name=source_sn,json=sourceSn,proto3" json:"source_sn,omitempty"`
	CreateTime string  `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Amount     float64 `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	UserName   string  `protobuf:"bytes,7,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *UserBalanceLog) Reset() {
	*x = UserBalanceLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBalanceLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceLog) ProtoMessage() {}

func (x *UserBalanceLog) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceLog.ProtoReflect.Descriptor instead.
func (*UserBalanceLog) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{1}
}

func (x *UserBalanceLog) GetBalanceId() int64 {
	if x != nil {
		return x.BalanceId
	}
	return 0
}

func (x *UserBalanceLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBalanceLog) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *UserBalanceLog) GetSourceSn() int64 {
	if x != nil {
		return x.SourceSn
	}
	return 0
}

func (x *UserBalanceLog) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserBalanceLog) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserBalanceLog) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type In_GetUserBalanceInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//通过id
	BalanceId int64 `protobuf:"varint,1,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
}

func (x *In_GetUserBalanceInfoById) Reset() {
	*x = In_GetUserBalanceInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserBalanceInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserBalanceInfoById) ProtoMessage() {}

func (x *In_GetUserBalanceInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserBalanceInfoById.ProtoReflect.Descriptor instead.
func (*In_GetUserBalanceInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{2}
}

func (x *In_GetUserBalanceInfoById) GetBalanceId() int64 {
	if x != nil {
		return x.BalanceId
	}
	return 0
}

type Out_GetUserBalanceInfoById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error          *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserBalanceLog *UserBalanceLog `protobuf:"bytes,2,opt,name=user_balance_log,json=userBalanceLog,proto3" json:"user_balance_log,omitempty"`
}

func (x *Out_GetUserBalanceInfoById) Reset() {
	*x = Out_GetUserBalanceInfoById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserBalanceInfoById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserBalanceInfoById) ProtoMessage() {}

func (x *Out_GetUserBalanceInfoById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserBalanceInfoById.ProtoReflect.Descriptor instead.
func (*Out_GetUserBalanceInfoById) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{3}
}

func (x *Out_GetUserBalanceInfoById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserBalanceInfoById) GetUserBalanceLog() *UserBalanceLog {
	if x != nil {
		return x.UserBalanceLog
	}
	return nil
}

type Out_UpdateUserBalanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error          *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserBalanceLog *UserBalanceLog `protobuf:"bytes,2,opt,name=user_balance_log,json=userBalanceLog,proto3" json:"user_balance_log,omitempty"`
}

func (x *Out_UpdateUserBalanceInfo) Reset() {
	*x = Out_UpdateUserBalanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateUserBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateUserBalanceInfo) ProtoMessage() {}

func (x *Out_UpdateUserBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateUserBalanceInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateUserBalanceInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{4}
}

func (x *Out_UpdateUserBalanceInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateUserBalanceInfo) GetUserBalanceLog() *UserBalanceLog {
	if x != nil {
		return x.UserBalanceLog
	}
	return nil
}

type In_UpdateUserBalanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBalanceLog *UserBalanceLog `protobuf:"bytes,1,opt,name=user_balance_log,json=userBalanceLog,proto3" json:"user_balance_log,omitempty"`
}

func (x *In_UpdateUserBalanceInfo) Reset() {
	*x = In_UpdateUserBalanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateUserBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateUserBalanceInfo) ProtoMessage() {}

func (x *In_UpdateUserBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateUserBalanceInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateUserBalanceInfo) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{5}
}

func (x *In_UpdateUserBalanceInfo) GetUserBalanceLog() *UserBalanceLog {
	if x != nil {
		return x.UserBalanceLog
	}
	return nil
}

type In_GetUserBalances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetUserBalances) Reset() {
	*x = In_GetUserBalances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetUserBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetUserBalances) ProtoMessage() {}

func (x *In_GetUserBalances) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetUserBalances.ProtoReflect.Descriptor instead.
func (*In_GetUserBalances) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{6}
}

func (x *In_GetUserBalances) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetUserBalances) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetUserBalances) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetUserBalances) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetUserBalances) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetUserBalances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error              *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit              int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages              int64             `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total              int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserBalanceLogList []*UserBalanceLog `protobuf:"bytes,5,rep,name=user_balance_log_list,json=userBalanceLogList,proto3" json:"user_balance_log_list,omitempty"`
}

func (x *Out_GetUserBalances) Reset() {
	*x = Out_GetUserBalances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetUserBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetUserBalances) ProtoMessage() {}

func (x *Out_GetUserBalances) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetUserBalances.ProtoReflect.Descriptor instead.
func (*Out_GetUserBalances) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{7}
}

func (x *Out_GetUserBalances) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetUserBalances) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetUserBalances) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetUserBalances) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetUserBalances) GetUserBalanceLogList() []*UserBalanceLog {
	if x != nil {
		return x.UserBalanceLogList
	}
	return nil
}

type In_DeleteUserBalances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBalanceLogs []int64 `protobuf:"varint,1,rep,packed,name=user_balance_logs,json=userBalanceLogs,proto3" json:"user_balance_logs,omitempty"`
}

func (x *In_DeleteUserBalances) Reset() {
	*x = In_DeleteUserBalances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteUserBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteUserBalances) ProtoMessage() {}

func (x *In_DeleteUserBalances) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteUserBalances.ProtoReflect.Descriptor instead.
func (*In_DeleteUserBalances) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{8}
}

func (x *In_DeleteUserBalances) GetUserBalanceLogs() []int64 {
	if x != nil {
		return x.UserBalanceLogs
	}
	return nil
}

type Out_DeleteUserBalances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteUserBalances) Reset() {
	*x = Out_DeleteUserBalances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteUserBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteUserBalances) ProtoMessage() {}

func (x *Out_DeleteUserBalances) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteUserBalances.ProtoReflect.Descriptor instead.
func (*Out_DeleteUserBalances) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{9}
}

func (x *Out_DeleteUserBalances) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateUserBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBalanceLog *UserBalanceLog `protobuf:"bytes,1,opt,name=user_balance_log,json=userBalanceLog,proto3" json:"user_balance_log,omitempty"`
}

func (x *In_CreateUserBalance) Reset() {
	*x = In_CreateUserBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateUserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateUserBalance) ProtoMessage() {}

func (x *In_CreateUserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateUserBalance.ProtoReflect.Descriptor instead.
func (*In_CreateUserBalance) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{10}
}

func (x *In_CreateUserBalance) GetUserBalanceLog() *UserBalanceLog {
	if x != nil {
		return x.UserBalanceLog
	}
	return nil
}

type Out_CreateUserBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error          *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserBalanceLog *UserBalanceLog `protobuf:"bytes,2,opt,name=user_balance_log,json=userBalanceLog,proto3" json:"user_balance_log,omitempty"` //等级信息
}

func (x *Out_CreateUserBalance) Reset() {
	*x = Out_CreateUserBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateUserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateUserBalance) ProtoMessage() {}

func (x *Out_CreateUserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateUserBalance.ProtoReflect.Descriptor instead.
func (*Out_CreateUserBalance) Descriptor() ([]byte, []int) {
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP(), []int{11}
}

func (x *Out_CreateUserBalance) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateUserBalance) GetUserBalanceLog() *UserBalanceLog {
	if x != nil {
		return x.UserBalanceLog
	}
	return nil
}

var File_modules_user_user_balance_log_user_balance_log_proto protoreflect.FileDescriptor

var file_modules_user_user_balance_log_user_balance_log_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0xd5, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x19, 0x49, 0x6e, 0x5f, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x1a, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x4c, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x52,
	0x0e, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x22,
	0x98, 0x01, 0x0a, 0x19, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x10,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x22, 0x68, 0x0a, 0x18, 0x49, 0x6e,
	0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4c, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xdd, 0x01, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x55, 0x0a, 0x15, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x12, 0x75, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x43, 0x0a, 0x15, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x73, 0x22, 0x47, 0x0a, 0x16, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12,
	0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x64,
	0x0a, 0x14, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x22, 0x94, 0x01, 0x0a, 0x15, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2d,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4c, 0x0a,
	0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x5f,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x52, 0x0e, 0x75, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x32, 0xb4, 0x04, 0x0a, 0x12,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x75, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x2c, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74,
	0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2b,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x60, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6c, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x69, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x28,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c,
	0x6f, 0x67, 0x2e, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x00, 0x42, 0x58, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x69, 0x61, 0x6e, 0x78, 0x75,
	0x6e, 0x6b, 0x65, 0x2e, 0x65, 0x67, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x42, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x50, 0x01, 0x5a, 0x1c, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0xa2, 0x02, 0x08, 0x55, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_user_user_balance_log_user_balance_log_proto_rawDescOnce sync.Once
	file_modules_user_user_balance_log_user_balance_log_proto_rawDescData = file_modules_user_user_balance_log_user_balance_log_proto_rawDesc
)

func file_modules_user_user_balance_log_user_balance_log_proto_rawDescGZIP() []byte {
	file_modules_user_user_balance_log_user_balance_log_proto_rawDescOnce.Do(func() {
		file_modules_user_user_balance_log_user_balance_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_user_user_balance_log_user_balance_log_proto_rawDescData)
	})
	return file_modules_user_user_balance_log_user_balance_log_proto_rawDescData
}

var file_modules_user_user_balance_log_user_balance_log_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_modules_user_user_balance_log_user_balance_log_proto_goTypes = []interface{}{
	(*Error)(nil),                      // 0: user_balance_log.Error
	(*UserBalanceLog)(nil),             // 1: user_balance_log.User_balance_log
	(*In_GetUserBalanceInfoById)(nil),  // 2: user_balance_log.In_GetUserBalanceInfoById
	(*Out_GetUserBalanceInfoById)(nil), // 3: user_balance_log.Out_GetUserBalanceInfoById
	(*Out_UpdateUserBalanceInfo)(nil),  // 4: user_balance_log.Out_UpdateUserBalanceInfo
	(*In_UpdateUserBalanceInfo)(nil),   // 5: user_balance_log.In_UpdateUserBalanceInfo
	(*In_GetUserBalances)(nil),         // 6: user_balance_log.In_GetUserBalances
	(*Out_GetUserBalances)(nil),        // 7: user_balance_log.Out_GetUserBalances
	(*In_DeleteUserBalances)(nil),      // 8: user_balance_log.In_DeleteUserBalances
	(*Out_DeleteUserBalances)(nil),     // 9: user_balance_log.Out_DeleteUserBalances
	(*In_CreateUserBalance)(nil),       // 10: user_balance_log.In_CreateUserBalance
	(*Out_CreateUserBalance)(nil),      // 11: user_balance_log.Out_CreateUserBalance
}
var file_modules_user_user_balance_log_user_balance_log_proto_depIdxs = []int32{
	0,  // 0: user_balance_log.Out_GetUserBalanceInfoById.error:type_name -> user_balance_log.Error
	1,  // 1: user_balance_log.Out_GetUserBalanceInfoById.user_balance_log:type_name -> user_balance_log.User_balance_log
	0,  // 2: user_balance_log.Out_UpdateUserBalanceInfo.error:type_name -> user_balance_log.Error
	1,  // 3: user_balance_log.Out_UpdateUserBalanceInfo.user_balance_log:type_name -> user_balance_log.User_balance_log
	1,  // 4: user_balance_log.In_UpdateUserBalanceInfo.user_balance_log:type_name -> user_balance_log.User_balance_log
	0,  // 5: user_balance_log.Out_GetUserBalances.error:type_name -> user_balance_log.Error
	1,  // 6: user_balance_log.Out_GetUserBalances.user_balance_log_list:type_name -> user_balance_log.User_balance_log
	0,  // 7: user_balance_log.Out_DeleteUserBalances.error:type_name -> user_balance_log.Error
	1,  // 8: user_balance_log.In_CreateUserBalance.user_balance_log:type_name -> user_balance_log.User_balance_log
	0,  // 9: user_balance_log.Out_CreateUserBalance.error:type_name -> user_balance_log.Error
	1,  // 10: user_balance_log.Out_CreateUserBalance.user_balance_log:type_name -> user_balance_log.User_balance_log
	2,  // 11: user_balance_log.UserBalanceService.GetUserBalanceInfoById:input_type -> user_balance_log.In_GetUserBalanceInfoById
	5,  // 12: user_balance_log.UserBalanceService.UpdateUserBalanceInfo:input_type -> user_balance_log.In_UpdateUserBalanceInfo
	6,  // 13: user_balance_log.UserBalanceService.GetUserBalances:input_type -> user_balance_log.In_GetUserBalances
	8,  // 14: user_balance_log.UserBalanceService.DeleteUserBalances:input_type -> user_balance_log.In_DeleteUserBalances
	10, // 15: user_balance_log.UserBalanceService.CreateUserBalance:input_type -> user_balance_log.In_CreateUserBalance
	3,  // 16: user_balance_log.UserBalanceService.GetUserBalanceInfoById:output_type -> user_balance_log.Out_GetUserBalanceInfoById
	4,  // 17: user_balance_log.UserBalanceService.UpdateUserBalanceInfo:output_type -> user_balance_log.Out_UpdateUserBalanceInfo
	7,  // 18: user_balance_log.UserBalanceService.GetUserBalances:output_type -> user_balance_log.Out_GetUserBalances
	9,  // 19: user_balance_log.UserBalanceService.DeleteUserBalances:output_type -> user_balance_log.Out_DeleteUserBalances
	11, // 20: user_balance_log.UserBalanceService.CreateUserBalance:output_type -> user_balance_log.Out_CreateUserBalance
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_modules_user_user_balance_log_user_balance_log_proto_init() }
func file_modules_user_user_balance_log_user_balance_log_proto_init() {
	if File_modules_user_user_balance_log_user_balance_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBalanceLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserBalanceInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserBalanceInfoById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateUserBalanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateUserBalanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetUserBalances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetUserBalances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteUserBalances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteUserBalances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateUserBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_user_user_balance_log_user_balance_log_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateUserBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_user_user_balance_log_user_balance_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_user_user_balance_log_user_balance_log_proto_goTypes,
		DependencyIndexes: file_modules_user_user_balance_log_user_balance_log_proto_depIdxs,
		MessageInfos:      file_modules_user_user_balance_log_user_balance_log_proto_msgTypes,
	}.Build()
	File_modules_user_user_balance_log_user_balance_log_proto = out.File
	file_modules_user_user_balance_log_user_balance_log_proto_rawDesc = nil
	file_modules_user_user_balance_log_user_balance_log_proto_goTypes = nil
	file_modules_user_user_balance_log_user_balance_log_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserBalanceServiceClient is the client API for UserBalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserBalanceServiceClient interface {
	//获取信息
	GetUserBalanceInfoById(ctx context.Context, in *In_GetUserBalanceInfoById, opts ...grpc.CallOption) (*Out_GetUserBalanceInfoById, error)
	//修改信息
	UpdateUserBalanceInfo(ctx context.Context, in *In_UpdateUserBalanceInfo, opts ...grpc.CallOption) (*Out_UpdateUserBalanceInfo, error)
	//获取列表
	GetUserBalances(ctx context.Context, in *In_GetUserBalances, opts ...grpc.CallOption) (*Out_GetUserBalances, error)
	//删除列表
	DeleteUserBalances(ctx context.Context, in *In_DeleteUserBalances, opts ...grpc.CallOption) (*Out_DeleteUserBalances, error)
	//新建信息
	CreateUserBalance(ctx context.Context, in *In_CreateUserBalance, opts ...grpc.CallOption) (*Out_CreateUserBalance, error)
}

type userBalanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserBalanceServiceClient(cc grpc.ClientConnInterface) UserBalanceServiceClient {
	return &userBalanceServiceClient{cc}
}

func (c *userBalanceServiceClient) GetUserBalanceInfoById(ctx context.Context, in *In_GetUserBalanceInfoById, opts ...grpc.CallOption) (*Out_GetUserBalanceInfoById, error) {
	out := new(Out_GetUserBalanceInfoById)
	err := c.cc.Invoke(ctx, "/user_balance_log.UserBalanceService/GetUserBalanceInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) UpdateUserBalanceInfo(ctx context.Context, in *In_UpdateUserBalanceInfo, opts ...grpc.CallOption) (*Out_UpdateUserBalanceInfo, error) {
	out := new(Out_UpdateUserBalanceInfo)
	err := c.cc.Invoke(ctx, "/user_balance_log.UserBalanceService/UpdateUserBalanceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) GetUserBalances(ctx context.Context, in *In_GetUserBalances, opts ...grpc.CallOption) (*Out_GetUserBalances, error) {
	out := new(Out_GetUserBalances)
	err := c.cc.Invoke(ctx, "/user_balance_log.UserBalanceService/GetUserBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) DeleteUserBalances(ctx context.Context, in *In_DeleteUserBalances, opts ...grpc.CallOption) (*Out_DeleteUserBalances, error) {
	out := new(Out_DeleteUserBalances)
	err := c.cc.Invoke(ctx, "/user_balance_log.UserBalanceService/DeleteUserBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) CreateUserBalance(ctx context.Context, in *In_CreateUserBalance, opts ...grpc.CallOption) (*Out_CreateUserBalance, error) {
	out := new(Out_CreateUserBalance)
	err := c.cc.Invoke(ctx, "/user_balance_log.UserBalanceService/CreateUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserBalanceServiceServer is the server API for UserBalanceService service.
type UserBalanceServiceServer interface {
	//获取信息
	GetUserBalanceInfoById(context.Context, *In_GetUserBalanceInfoById) (*Out_GetUserBalanceInfoById, error)
	//修改信息
	UpdateUserBalanceInfo(context.Context, *In_UpdateUserBalanceInfo) (*Out_UpdateUserBalanceInfo, error)
	//获取列表
	GetUserBalances(context.Context, *In_GetUserBalances) (*Out_GetUserBalances, error)
	//删除列表
	DeleteUserBalances(context.Context, *In_DeleteUserBalances) (*Out_DeleteUserBalances, error)
	//新建信息
	CreateUserBalance(context.Context, *In_CreateUserBalance) (*Out_CreateUserBalance, error)
}

// UnimplementedUserBalanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserBalanceServiceServer struct {
}

func (*UnimplementedUserBalanceServiceServer) GetUserBalanceInfoById(context.Context, *In_GetUserBalanceInfoById) (*Out_GetUserBalanceInfoById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalanceInfoById not implemented")
}
func (*UnimplementedUserBalanceServiceServer) UpdateUserBalanceInfo(context.Context, *In_UpdateUserBalanceInfo) (*Out_UpdateUserBalanceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserBalanceInfo not implemented")
}
func (*UnimplementedUserBalanceServiceServer) GetUserBalances(context.Context, *In_GetUserBalances) (*Out_GetUserBalances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalances not implemented")
}
func (*UnimplementedUserBalanceServiceServer) DeleteUserBalances(context.Context, *In_DeleteUserBalances) (*Out_DeleteUserBalances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserBalances not implemented")
}
func (*UnimplementedUserBalanceServiceServer) CreateUserBalance(context.Context, *In_CreateUserBalance) (*Out_CreateUserBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserBalance not implemented")
}

func RegisterUserBalanceServiceServer(s *grpc.Server, srv UserBalanceServiceServer) {
	s.RegisterService(&_UserBalanceService_serviceDesc, srv)
}

func _UserBalanceService_GetUserBalanceInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserBalanceInfoById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).GetUserBalanceInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_balance_log.UserBalanceService/GetUserBalanceInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).GetUserBalanceInfoById(ctx, req.(*In_GetUserBalanceInfoById))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_UpdateUserBalanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateUserBalanceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).UpdateUserBalanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_balance_log.UserBalanceService/UpdateUserBalanceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).UpdateUserBalanceInfo(ctx, req.(*In_UpdateUserBalanceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_GetUserBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetUserBalances)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).GetUserBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_balance_log.UserBalanceService/GetUserBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).GetUserBalances(ctx, req.(*In_GetUserBalances))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_DeleteUserBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteUserBalances)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).DeleteUserBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_balance_log.UserBalanceService/DeleteUserBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).DeleteUserBalances(ctx, req.(*In_DeleteUserBalances))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_CreateUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateUserBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).CreateUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_balance_log.UserBalanceService/CreateUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).CreateUserBalance(ctx, req.(*In_CreateUserBalance))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserBalanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_balance_log.UserBalanceService",
	HandlerType: (*UserBalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBalanceInfoById",
			Handler:    _UserBalanceService_GetUserBalanceInfoById_Handler,
		},
		{
			MethodName: "UpdateUserBalanceInfo",
			Handler:    _UserBalanceService_UpdateUserBalanceInfo_Handler,
		},
		{
			MethodName: "GetUserBalances",
			Handler:    _UserBalanceService_GetUserBalances_Handler,
		},
		{
			MethodName: "DeleteUserBalances",
			Handler:    _UserBalanceService_DeleteUserBalances_Handler,
		},
		{
			MethodName: "CreateUserBalance",
			Handler:    _UserBalanceService_CreateUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/user/user_balance_log/user_balance_log.proto",
}
