// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/inventory/product_category/product_category.proto

package product_category

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type ProductCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId     int64  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` //上级分类的编号：0表示一级分类
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level        string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`                                   //分类级别：0->1级；1->2级
	ProductCount string `protobuf:"bytes,5,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"` //
	ProductUnit  int64  `protobuf:"varint,6,opt,name=product_unit,json=productUnit,proto3" json:"product_unit,omitempty"`   //
	NavStatus    int64  `protobuf:"varint,7,opt,name=nav_status,json=navStatus,proto3" json:"nav_status,omitempty"`         //是否显示在导航栏：0->不显示；1->显示
	ShowStatus   int64  `protobuf:"varint,8,opt,name=show_status,json=showStatus,proto3" json:"show_status,omitempty"`      //显示状态：0->不显示；1->显示
	Sort         int64  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`                                    //
	Icon         string `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`                                    //图标
	Keywords     string `protobuf:"bytes,11,opt,name=keywords,proto3" json:"keywords,omitempty"`                            //
	Description  string `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CreatedTime  string `protobuf:"bytes,13,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
}

func (x *ProductCategory) Reset() {
	*x = ProductCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategory) ProtoMessage() {}

func (x *ProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategory.ProtoReflect.Descriptor instead.
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductCategory) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ProductCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategory) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ProductCategory) GetProductCount() string {
	if x != nil {
		return x.ProductCount
	}
	return ""
}

func (x *ProductCategory) GetProductUnit() int64 {
	if x != nil {
		return x.ProductUnit
	}
	return 0
}

func (x *ProductCategory) GetNavStatus() int64 {
	if x != nil {
		return x.NavStatus
	}
	return 0
}

func (x *ProductCategory) GetShowStatus() int64 {
	if x != nil {
		return x.ShowStatus
	}
	return 0
}

func (x *ProductCategory) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductCategory) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ProductCategory) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ProductCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCategory) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

type ProductCategoryDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChildId   int64  `protobuf:"varint,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ChildName string `protobuf:"bytes,4,opt,name=child_name,json=childName,proto3" json:"child_name,omitempty"`
}

func (x *ProductCategoryDetails) Reset() {
	*x = ProductCategoryDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCategoryDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategoryDetails) ProtoMessage() {}

func (x *ProductCategoryDetails) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategoryDetails.ProtoReflect.Descriptor instead.
func (*ProductCategoryDetails) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCategoryDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductCategoryDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategoryDetails) GetChildId() int64 {
	if x != nil {
		return x.ChildId
	}
	return 0
}

func (x *ProductCategoryDetails) GetChildName() string {
	if x != nil {
		return x.ChildName
	}
	return ""
}

type Out_GetProductCategoryDetailsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error               *Error                    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit               int64                     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages               int64                     `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total               int64                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductCategoryList []*ProductCategoryDetails `protobuf:"bytes,5,rep,name=product_category_list,json=productCategoryList,proto3" json:"product_category_list,omitempty"`
}

func (x *Out_GetProductCategoryDetailsList) Reset() {
	*x = Out_GetProductCategoryDetailsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductCategoryDetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductCategoryDetailsList) ProtoMessage() {}

func (x *Out_GetProductCategoryDetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductCategoryDetailsList.ProtoReflect.Descriptor instead.
func (*Out_GetProductCategoryDetailsList) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{2}
}

func (x *Out_GetProductCategoryDetailsList) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductCategoryDetailsList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetProductCategoryDetailsList) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetProductCategoryDetailsList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetProductCategoryDetailsList) GetProductCategoryList() []*ProductCategoryDetails {
	if x != nil {
		return x.ProductCategoryList
	}
	return nil
}

type In_GetProductCategoryDetailsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *In_GetProductCategoryDetailsList) Reset() {
	*x = In_GetProductCategoryDetailsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductCategoryDetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductCategoryDetailsList) ProtoMessage() {}

func (x *In_GetProductCategoryDetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductCategoryDetailsList.ProtoReflect.Descriptor instead.
func (*In_GetProductCategoryDetailsList) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type In_GetProductCategoryById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *In_GetProductCategoryById) Reset() {
	*x = In_GetProductCategoryById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductCategoryById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductCategoryById) ProtoMessage() {}

func (x *In_GetProductCategoryById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductCategoryById.ProtoReflect.Descriptor instead.
func (*In_GetProductCategoryById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{5}
}

func (x *In_GetProductCategoryById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Out_GetProductCategoryById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error           *Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductCategory *ProductCategory `protobuf:"bytes,2,opt,name=product_category,json=productCategory,proto3" json:"product_category,omitempty"`
}

func (x *Out_GetProductCategoryById) Reset() {
	*x = Out_GetProductCategoryById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductCategoryById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductCategoryById) ProtoMessage() {}

func (x *Out_GetProductCategoryById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductCategoryById.ProtoReflect.Descriptor instead.
func (*Out_GetProductCategoryById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{6}
}

func (x *Out_GetProductCategoryById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductCategoryById) GetProductCategory() *ProductCategory {
	if x != nil {
		return x.ProductCategory
	}
	return nil
}

type Out_UpdateProductCategoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error           *Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductCategory *ProductCategory `protobuf:"bytes,2,opt,name=product_category,json=productCategory,proto3" json:"product_category,omitempty"`
}

func (x *Out_UpdateProductCategoryInfo) Reset() {
	*x = Out_UpdateProductCategoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateProductCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateProductCategoryInfo) ProtoMessage() {}

func (x *Out_UpdateProductCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateProductCategoryInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateProductCategoryInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{7}
}

func (x *Out_UpdateProductCategoryInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateProductCategoryInfo) GetProductCategory() *ProductCategory {
	if x != nil {
		return x.ProductCategory
	}
	return nil
}

type In_UpdateProductCategoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductCategory *ProductCategory `protobuf:"bytes,1,opt,name=product_category,json=productCategory,proto3" json:"product_category,omitempty"`
}

func (x *In_UpdateProductCategoryInfo) Reset() {
	*x = In_UpdateProductCategoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateProductCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateProductCategoryInfo) ProtoMessage() {}

func (x *In_UpdateProductCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateProductCategoryInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateProductCategoryInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{8}
}

func (x *In_UpdateProductCategoryInfo) GetProductCategory() *ProductCategory {
	if x != nil {
		return x.ProductCategory
	}
	return nil
}

type In_GetProductCategorys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetProductCategorys) Reset() {
	*x = In_GetProductCategorys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductCategorys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductCategorys) ProtoMessage() {}

func (x *In_GetProductCategorys) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductCategorys.ProtoReflect.Descriptor instead.
func (*In_GetProductCategorys) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{9}
}

func (x *In_GetProductCategorys) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetProductCategorys) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetProductCategorys) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetProductCategorys) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetProductCategorys) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetProductCategorys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error               *Error             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit               int64              `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages               int64              `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total               int64              `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductCategoryList []*ProductCategory `protobuf:"bytes,5,rep,name=product_category_list,json=productCategoryList,proto3" json:"product_category_list,omitempty"`
}

func (x *Out_GetProductCategorys) Reset() {
	*x = Out_GetProductCategorys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductCategorys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductCategorys) ProtoMessage() {}

func (x *Out_GetProductCategorys) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductCategorys.ProtoReflect.Descriptor instead.
func (*Out_GetProductCategorys) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{10}
}

func (x *Out_GetProductCategorys) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductCategorys) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetProductCategorys) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetProductCategorys) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetProductCategorys) GetProductCategoryList() []*ProductCategory {
	if x != nil {
		return x.ProductCategoryList
	}
	return nil
}

type In_DeleteProductCategorys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductCategoryList []int64 `protobuf:"varint,1,rep,packed,name=product_category_list,json=productCategoryList,proto3" json:"product_category_list,omitempty"`
}

func (x *In_DeleteProductCategorys) Reset() {
	*x = In_DeleteProductCategorys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteProductCategorys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteProductCategorys) ProtoMessage() {}

func (x *In_DeleteProductCategorys) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteProductCategorys.ProtoReflect.Descriptor instead.
func (*In_DeleteProductCategorys) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{11}
}

func (x *In_DeleteProductCategorys) GetProductCategoryList() []int64 {
	if x != nil {
		return x.ProductCategoryList
	}
	return nil
}

type Out_DeleteProductCategorys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteProductCategorys) Reset() {
	*x = Out_DeleteProductCategorys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteProductCategorys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteProductCategorys) ProtoMessage() {}

func (x *Out_DeleteProductCategorys) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteProductCategorys.ProtoReflect.Descriptor instead.
func (*Out_DeleteProductCategorys) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{12}
}

func (x *Out_DeleteProductCategorys) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateProductCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductCategory *ProductCategory `protobuf:"bytes,1,opt,name=product_category,json=productCategory,proto3" json:"product_category,omitempty"`
}

func (x *In_CreateProductCategory) Reset() {
	*x = In_CreateProductCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateProductCategory) ProtoMessage() {}

func (x *In_CreateProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateProductCategory.ProtoReflect.Descriptor instead.
func (*In_CreateProductCategory) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{13}
}

func (x *In_CreateProductCategory) GetProductCategory() *ProductCategory {
	if x != nil {
		return x.ProductCategory
	}
	return nil
}

type Out_CreateProductCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error           *Error           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductCategory *ProductCategory `protobuf:"bytes,2,opt,name=product_category,json=productCategory,proto3" json:"product_category,omitempty"`
}

func (x *Out_CreateProductCategory) Reset() {
	*x = Out_CreateProductCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateProductCategory) ProtoMessage() {}

func (x *Out_CreateProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_category_product_category_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateProductCategory.ProtoReflect.Descriptor instead.
func (*Out_CreateProductCategory) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_category_product_category_proto_rawDescGZIP(), []int{14}
}

func (x *Out_CreateProductCategory) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateProductCategory) GetProductCategory() *ProductCategory {
	if x != nil {
		return x.ProductCategory
	}
	return nil
}

var File_modules_inventory_product_category_product_category_proto protoreflect.FileDescriptor

var file_modules_inventory_product_category_product_category_proto_rawDesc = []byte{
	0x0a, 0x39, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xfa, 0x02,
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x76, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x61, 0x76, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x78, 0x0a, 0x18, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x21, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x5e, 0x0a, 0x15, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x20, 0x49,
	0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x19, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x4d, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x22, 0x9d, 0x01, 0x0a, 0x1d, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x4d, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x22, 0x6d, 0x0a, 0x1c, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x4d, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x9d, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xe2, 0x01, 0x0a, 0x17, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x56, 0x0a, 0x15,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x19, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x73, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x1a, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x69, 0x0a, 0x18, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x4d,
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x99, 0x01,
	0x0a, 0x19, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4d, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0xf5, 0x05, 0x0a, 0x16, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x75, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2b,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x4f,
	0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x6e, 0x5f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x5f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x73, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73, 0x1a, 0x29, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e,
	0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x73, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73,
	0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x73, 0x22, 0x00,
	0x12, 0x72, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x6e, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x22, 0x00, 0x12, 0x8a, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x4f, 0x75,
	0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x42, 0x64, 0x0a, 0x2c, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x69, 0x61, 0x6e, 0x78, 0x75, 0x6e,
	0x6b, 0x65, 0x2e, 0x65, 0x67, 0x6f, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x42, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_inventory_product_category_product_category_proto_rawDescOnce sync.Once
	file_modules_inventory_product_category_product_category_proto_rawDescData = file_modules_inventory_product_category_product_category_proto_rawDesc
)

func file_modules_inventory_product_category_product_category_proto_rawDescGZIP() []byte {
	file_modules_inventory_product_category_product_category_proto_rawDescOnce.Do(func() {
		file_modules_inventory_product_category_product_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_inventory_product_category_product_category_proto_rawDescData)
	})
	return file_modules_inventory_product_category_product_category_proto_rawDescData
}

var file_modules_inventory_product_category_product_category_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_modules_inventory_product_category_product_category_proto_goTypes = []interface{}{
	(*ProductCategory)(nil),                   // 0: product_category.Product_category
	(*ProductCategoryDetails)(nil),            // 1: product_category.Product_category_details
	(*Out_GetProductCategoryDetailsList)(nil), // 2: product_category.Out_GetProductCategoryDetailsList
	(*In_GetProductCategoryDetailsList)(nil),  // 3: product_category.In_GetProductCategoryDetailsList
	(*Error)(nil),                             // 4: product_category.Error
	(*In_GetProductCategoryById)(nil),         // 5: product_category.In_GetProductCategoryById
	(*Out_GetProductCategoryById)(nil),        // 6: product_category.Out_GetProductCategoryById
	(*Out_UpdateProductCategoryInfo)(nil),     // 7: product_category.Out_UpdateProductCategoryInfo
	(*In_UpdateProductCategoryInfo)(nil),      // 8: product_category.In_UpdateProductCategoryInfo
	(*In_GetProductCategorys)(nil),            // 9: product_category.In_GetProductCategorys
	(*Out_GetProductCategorys)(nil),           // 10: product_category.Out_GetProductCategorys
	(*In_DeleteProductCategorys)(nil),         // 11: product_category.In_DeleteProductCategorys
	(*Out_DeleteProductCategorys)(nil),        // 12: product_category.Out_DeleteProductCategorys
	(*In_CreateProductCategory)(nil),          // 13: product_category.In_CreateProductCategory
	(*Out_CreateProductCategory)(nil),         // 14: product_category.Out_CreateProductCategory
}
var file_modules_inventory_product_category_product_category_proto_depIdxs = []int32{
	4,  // 0: product_category.Out_GetProductCategoryDetailsList.error:type_name -> product_category.Error
	1,  // 1: product_category.Out_GetProductCategoryDetailsList.product_category_list:type_name -> product_category.Product_category_details
	4,  // 2: product_category.Out_GetProductCategoryById.error:type_name -> product_category.Error
	0,  // 3: product_category.Out_GetProductCategoryById.product_category:type_name -> product_category.Product_category
	4,  // 4: product_category.Out_UpdateProductCategoryInfo.error:type_name -> product_category.Error
	0,  // 5: product_category.Out_UpdateProductCategoryInfo.product_category:type_name -> product_category.Product_category
	0,  // 6: product_category.In_UpdateProductCategoryInfo.product_category:type_name -> product_category.Product_category
	4,  // 7: product_category.Out_GetProductCategorys.error:type_name -> product_category.Error
	0,  // 8: product_category.Out_GetProductCategorys.product_category_list:type_name -> product_category.Product_category
	4,  // 9: product_category.Out_DeleteProductCategorys.error:type_name -> product_category.Error
	0,  // 10: product_category.In_CreateProductCategory.product_category:type_name -> product_category.Product_category
	4,  // 11: product_category.Out_CreateProductCategory.error:type_name -> product_category.Error
	0,  // 12: product_category.Out_CreateProductCategory.product_category:type_name -> product_category.Product_category
	5,  // 13: product_category.ProductCategoryHandler.GetProductCategoryById:input_type -> product_category.In_GetProductCategoryById
	8,  // 14: product_category.ProductCategoryHandler.UpdateProductCategoryInfo:input_type -> product_category.In_UpdateProductCategoryInfo
	9,  // 15: product_category.ProductCategoryHandler.GetProductCategorys:input_type -> product_category.In_GetProductCategorys
	11, // 16: product_category.ProductCategoryHandler.DeleteProductCategorys:input_type -> product_category.In_DeleteProductCategorys
	13, // 17: product_category.ProductCategoryHandler.CreateProductCategory:input_type -> product_category.In_CreateProductCategory
	3,  // 18: product_category.ProductCategoryHandler.GetProductCategoryDetailsList:input_type -> product_category.In_GetProductCategoryDetailsList
	6,  // 19: product_category.ProductCategoryHandler.GetProductCategoryById:output_type -> product_category.Out_GetProductCategoryById
	7,  // 20: product_category.ProductCategoryHandler.UpdateProductCategoryInfo:output_type -> product_category.Out_UpdateProductCategoryInfo
	10, // 21: product_category.ProductCategoryHandler.GetProductCategorys:output_type -> product_category.Out_GetProductCategorys
	12, // 22: product_category.ProductCategoryHandler.DeleteProductCategorys:output_type -> product_category.Out_DeleteProductCategorys
	14, // 23: product_category.ProductCategoryHandler.CreateProductCategory:output_type -> product_category.Out_CreateProductCategory
	2,  // 24: product_category.ProductCategoryHandler.GetProductCategoryDetailsList:output_type -> product_category.Out_GetProductCategoryDetailsList
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_modules_inventory_product_category_product_category_proto_init() }
func file_modules_inventory_product_category_product_category_proto_init() {
	if File_modules_inventory_product_category_product_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_inventory_product_category_product_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCategoryDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductCategoryDetailsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductCategoryDetailsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductCategoryById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductCategoryById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateProductCategoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateProductCategoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductCategorys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductCategorys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteProductCategorys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteProductCategorys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateProductCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_category_product_category_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateProductCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_inventory_product_category_product_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_inventory_product_category_product_category_proto_goTypes,
		DependencyIndexes: file_modules_inventory_product_category_product_category_proto_depIdxs,
		MessageInfos:      file_modules_inventory_product_category_product_category_proto_msgTypes,
	}.Build()
	File_modules_inventory_product_category_product_category_proto = out.File
	file_modules_inventory_product_category_product_category_proto_rawDesc = nil
	file_modules_inventory_product_category_product_category_proto_goTypes = nil
	file_modules_inventory_product_category_product_category_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductCategoryHandlerClient is the client API for ProductCategoryHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductCategoryHandlerClient interface {
	//获取信息
	GetProductCategoryById(ctx context.Context, in *In_GetProductCategoryById, opts ...grpc.CallOption) (*Out_GetProductCategoryById, error)
	//修改信息
	UpdateProductCategoryInfo(ctx context.Context, in *In_UpdateProductCategoryInfo, opts ...grpc.CallOption) (*Out_UpdateProductCategoryInfo, error)
	//获取列表
	GetProductCategorys(ctx context.Context, in *In_GetProductCategorys, opts ...grpc.CallOption) (*Out_GetProductCategorys, error)
	//删除列表
	DeleteProductCategorys(ctx context.Context, in *In_DeleteProductCategorys, opts ...grpc.CallOption) (*Out_DeleteProductCategorys, error)
	//新建信息
	CreateProductCategory(ctx context.Context, in *In_CreateProductCategory, opts ...grpc.CallOption) (*Out_CreateProductCategory, error)
	//获取类别详情
	GetProductCategoryDetailsList(ctx context.Context, in *In_GetProductCategoryDetailsList, opts ...grpc.CallOption) (*Out_GetProductCategoryDetailsList, error)
}

type productCategoryHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCategoryHandlerClient(cc grpc.ClientConnInterface) ProductCategoryHandlerClient {
	return &productCategoryHandlerClient{cc}
}

func (c *productCategoryHandlerClient) GetProductCategoryById(ctx context.Context, in *In_GetProductCategoryById, opts ...grpc.CallOption) (*Out_GetProductCategoryById, error) {
	out := new(Out_GetProductCategoryById)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/GetProductCategoryById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryHandlerClient) UpdateProductCategoryInfo(ctx context.Context, in *In_UpdateProductCategoryInfo, opts ...grpc.CallOption) (*Out_UpdateProductCategoryInfo, error) {
	out := new(Out_UpdateProductCategoryInfo)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/UpdateProductCategoryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryHandlerClient) GetProductCategorys(ctx context.Context, in *In_GetProductCategorys, opts ...grpc.CallOption) (*Out_GetProductCategorys, error) {
	out := new(Out_GetProductCategorys)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/GetProductCategorys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryHandlerClient) DeleteProductCategorys(ctx context.Context, in *In_DeleteProductCategorys, opts ...grpc.CallOption) (*Out_DeleteProductCategorys, error) {
	out := new(Out_DeleteProductCategorys)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/DeleteProductCategorys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryHandlerClient) CreateProductCategory(ctx context.Context, in *In_CreateProductCategory, opts ...grpc.CallOption) (*Out_CreateProductCategory, error) {
	out := new(Out_CreateProductCategory)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/CreateProductCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCategoryHandlerClient) GetProductCategoryDetailsList(ctx context.Context, in *In_GetProductCategoryDetailsList, opts ...grpc.CallOption) (*Out_GetProductCategoryDetailsList, error) {
	out := new(Out_GetProductCategoryDetailsList)
	err := c.cc.Invoke(ctx, "/product_category.ProductCategoryHandler/GetProductCategoryDetailsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductCategoryHandlerServer is the server API for ProductCategoryHandler service.
type ProductCategoryHandlerServer interface {
	//获取信息
	GetProductCategoryById(context.Context, *In_GetProductCategoryById) (*Out_GetProductCategoryById, error)
	//修改信息
	UpdateProductCategoryInfo(context.Context, *In_UpdateProductCategoryInfo) (*Out_UpdateProductCategoryInfo, error)
	//获取列表
	GetProductCategorys(context.Context, *In_GetProductCategorys) (*Out_GetProductCategorys, error)
	//删除列表
	DeleteProductCategorys(context.Context, *In_DeleteProductCategorys) (*Out_DeleteProductCategorys, error)
	//新建信息
	CreateProductCategory(context.Context, *In_CreateProductCategory) (*Out_CreateProductCategory, error)
	//获取类别详情
	GetProductCategoryDetailsList(context.Context, *In_GetProductCategoryDetailsList) (*Out_GetProductCategoryDetailsList, error)
}

// UnimplementedProductCategoryHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedProductCategoryHandlerServer struct {
}

func (*UnimplementedProductCategoryHandlerServer) GetProductCategoryById(context.Context, *In_GetProductCategoryById) (*Out_GetProductCategoryById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCategoryById not implemented")
}
func (*UnimplementedProductCategoryHandlerServer) UpdateProductCategoryInfo(context.Context, *In_UpdateProductCategoryInfo) (*Out_UpdateProductCategoryInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductCategoryInfo not implemented")
}
func (*UnimplementedProductCategoryHandlerServer) GetProductCategorys(context.Context, *In_GetProductCategorys) (*Out_GetProductCategorys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCategorys not implemented")
}
func (*UnimplementedProductCategoryHandlerServer) DeleteProductCategorys(context.Context, *In_DeleteProductCategorys) (*Out_DeleteProductCategorys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductCategorys not implemented")
}
func (*UnimplementedProductCategoryHandlerServer) CreateProductCategory(context.Context, *In_CreateProductCategory) (*Out_CreateProductCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductCategory not implemented")
}
func (*UnimplementedProductCategoryHandlerServer) GetProductCategoryDetailsList(context.Context, *In_GetProductCategoryDetailsList) (*Out_GetProductCategoryDetailsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCategoryDetailsList not implemented")
}

func RegisterProductCategoryHandlerServer(s *grpc.Server, srv ProductCategoryHandlerServer) {
	s.RegisterService(&_ProductCategoryHandler_serviceDesc, srv)
}

func _ProductCategoryHandler_GetProductCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).GetProductCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/GetProductCategoryById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).GetProductCategoryById(ctx, req.(*In_GetProductCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryHandler_UpdateProductCategoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateProductCategoryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).UpdateProductCategoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/UpdateProductCategoryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).UpdateProductCategoryInfo(ctx, req.(*In_UpdateProductCategoryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryHandler_GetProductCategorys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductCategorys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).GetProductCategorys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/GetProductCategorys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).GetProductCategorys(ctx, req.(*In_GetProductCategorys))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryHandler_DeleteProductCategorys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteProductCategorys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).DeleteProductCategorys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/DeleteProductCategorys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).DeleteProductCategorys(ctx, req.(*In_DeleteProductCategorys))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryHandler_CreateProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateProductCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).CreateProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/CreateProductCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).CreateProductCategory(ctx, req.(*In_CreateProductCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCategoryHandler_GetProductCategoryDetailsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductCategoryDetailsList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCategoryHandlerServer).GetProductCategoryDetailsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_category.ProductCategoryHandler/GetProductCategoryDetailsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCategoryHandlerServer).GetProductCategoryDetailsList(ctx, req.(*In_GetProductCategoryDetailsList))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductCategoryHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product_category.ProductCategoryHandler",
	HandlerType: (*ProductCategoryHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductCategoryById",
			Handler:    _ProductCategoryHandler_GetProductCategoryById_Handler,
		},
		{
			MethodName: "UpdateProductCategoryInfo",
			Handler:    _ProductCategoryHandler_UpdateProductCategoryInfo_Handler,
		},
		{
			MethodName: "GetProductCategorys",
			Handler:    _ProductCategoryHandler_GetProductCategorys_Handler,
		},
		{
			MethodName: "DeleteProductCategorys",
			Handler:    _ProductCategoryHandler_DeleteProductCategorys_Handler,
		},
		{
			MethodName: "CreateProductCategory",
			Handler:    _ProductCategoryHandler_CreateProductCategory_Handler,
		},
		{
			MethodName: "GetProductCategoryDetailsList",
			Handler:    _ProductCategoryHandler_GetProductCategoryDetailsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/inventory/product_category/product_category.proto",
}
