// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/inventory/product_attribute_value/product_attribute_value.proto

package product_attribute_value

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type ProductAttributeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId          string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` //
	ProductAttributeId int64  `protobuf:"varint,3,opt,name=product_attribute_id,json=productAttributeId,proto3" json:"product_attribute_id,omitempty"`
	Value              string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProductAttributeValue) Reset() {
	*x = ProductAttributeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeValue) ProtoMessage() {}

func (x *ProductAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeValue.ProtoReflect.Descriptor instead.
func (*ProductAttributeValue) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAttributeValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAttributeValue) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductAttributeValue) GetProductAttributeId() int64 {
	if x != nil {
		return x.ProductAttributeId
	}
	return 0
}

func (x *ProductAttributeValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type In_GetProductAttributeValueById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *In_GetProductAttributeValueById) Reset() {
	*x = In_GetProductAttributeValueById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductAttributeValueById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductAttributeValueById) ProtoMessage() {}

func (x *In_GetProductAttributeValueById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductAttributeValueById.ProtoReflect.Descriptor instead.
func (*In_GetProductAttributeValueById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{2}
}

func (x *In_GetProductAttributeValueById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Out_GetProductAttributeValueById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                 *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttributeValue *ProductAttributeValue `protobuf:"bytes,2,opt,name=product_attribute_value,json=productAttributeValue,proto3" json:"product_attribute_value,omitempty"`
}

func (x *Out_GetProductAttributeValueById) Reset() {
	*x = Out_GetProductAttributeValueById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductAttributeValueById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductAttributeValueById) ProtoMessage() {}

func (x *Out_GetProductAttributeValueById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductAttributeValueById.ProtoReflect.Descriptor instead.
func (*Out_GetProductAttributeValueById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{3}
}

func (x *Out_GetProductAttributeValueById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductAttributeValueById) GetProductAttributeValue() *ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValue
	}
	return nil
}

type Out_UpdateProductAttributeValueInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                 *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttributeValue *ProductAttributeValue `protobuf:"bytes,2,opt,name=product_attribute_value,json=productAttributeValue,proto3" json:"product_attribute_value,omitempty"`
}

func (x *Out_UpdateProductAttributeValueInfo) Reset() {
	*x = Out_UpdateProductAttributeValueInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateProductAttributeValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateProductAttributeValueInfo) ProtoMessage() {}

func (x *Out_UpdateProductAttributeValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateProductAttributeValueInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateProductAttributeValueInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{4}
}

func (x *Out_UpdateProductAttributeValueInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateProductAttributeValueInfo) GetProductAttributeValue() *ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValue
	}
	return nil
}

type In_UpdateProductAttributeValueInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductAttributeValue *ProductAttributeValue `protobuf:"bytes,1,opt,name=product_attribute_value,json=productAttributeValue,proto3" json:"product_attribute_value,omitempty"`
}

func (x *In_UpdateProductAttributeValueInfo) Reset() {
	*x = In_UpdateProductAttributeValueInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateProductAttributeValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateProductAttributeValueInfo) ProtoMessage() {}

func (x *In_UpdateProductAttributeValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateProductAttributeValueInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateProductAttributeValueInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{5}
}

func (x *In_UpdateProductAttributeValueInfo) GetProductAttributeValue() *ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValue
	}
	return nil
}

type In_GetProductAttributeValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetProductAttributeValues) Reset() {
	*x = In_GetProductAttributeValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductAttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductAttributeValues) ProtoMessage() {}

func (x *In_GetProductAttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductAttributeValues.ProtoReflect.Descriptor instead.
func (*In_GetProductAttributeValues) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{6}
}

func (x *In_GetProductAttributeValues) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetProductAttributeValues) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetProductAttributeValues) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetProductAttributeValues) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetProductAttributeValues) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetProductAttributeValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                     *Error                   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                     int64                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                     int64                    `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                     int64                    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductAttributeValueList []*ProductAttributeValue `protobuf:"bytes,5,rep,name=product_attribute_value_list,json=productAttributeValueList,proto3" json:"product_attribute_value_list,omitempty"`
}

func (x *Out_GetProductAttributeValues) Reset() {
	*x = Out_GetProductAttributeValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductAttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductAttributeValues) ProtoMessage() {}

func (x *Out_GetProductAttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductAttributeValues.ProtoReflect.Descriptor instead.
func (*Out_GetProductAttributeValues) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{7}
}

func (x *Out_GetProductAttributeValues) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductAttributeValues) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetProductAttributeValues) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetProductAttributeValues) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetProductAttributeValues) GetProductAttributeValueList() []*ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValueList
	}
	return nil
}

type In_DeleteProductAttributeValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductAttributeValueList []int64 `protobuf:"varint,1,rep,packed,name=product_attribute_value_list,json=productAttributeValueList,proto3" json:"product_attribute_value_list,omitempty"`
}

func (x *In_DeleteProductAttributeValues) Reset() {
	*x = In_DeleteProductAttributeValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteProductAttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteProductAttributeValues) ProtoMessage() {}

func (x *In_DeleteProductAttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteProductAttributeValues.ProtoReflect.Descriptor instead.
func (*In_DeleteProductAttributeValues) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{8}
}

func (x *In_DeleteProductAttributeValues) GetProductAttributeValueList() []int64 {
	if x != nil {
		return x.ProductAttributeValueList
	}
	return nil
}

type Out_DeleteProductAttributeValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteProductAttributeValues) Reset() {
	*x = Out_DeleteProductAttributeValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteProductAttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteProductAttributeValues) ProtoMessage() {}

func (x *Out_DeleteProductAttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteProductAttributeValues.ProtoReflect.Descriptor instead.
func (*Out_DeleteProductAttributeValues) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{9}
}

func (x *Out_DeleteProductAttributeValues) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateProductAttributeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductAttributeValue *ProductAttributeValue `protobuf:"bytes,1,opt,name=product_attribute_value,json=productAttributeValue,proto3" json:"product_attribute_value,omitempty"`
}

func (x *In_CreateProductAttributeValue) Reset() {
	*x = In_CreateProductAttributeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateProductAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateProductAttributeValue) ProtoMessage() {}

func (x *In_CreateProductAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateProductAttributeValue.ProtoReflect.Descriptor instead.
func (*In_CreateProductAttributeValue) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{10}
}

func (x *In_CreateProductAttributeValue) GetProductAttributeValue() *ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValue
	}
	return nil
}

type Out_CreateProductAttributeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                 *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttributeValue *ProductAttributeValue `protobuf:"bytes,2,opt,name=product_attribute_value,json=productAttributeValue,proto3" json:"product_attribute_value,omitempty"`
}

func (x *Out_CreateProductAttributeValue) Reset() {
	*x = Out_CreateProductAttributeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateProductAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateProductAttributeValue) ProtoMessage() {}

func (x *Out_CreateProductAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateProductAttributeValue.ProtoReflect.Descriptor instead.
func (*Out_CreateProductAttributeValue) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP(), []int{11}
}

func (x *Out_CreateProductAttributeValue) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateProductAttributeValue) GetProductAttributeValue() *ProductAttributeValue {
	if x != nil {
		return x.ProductAttributeValue
	}
	return nil
}

var File_modules_inventory_product_attribute_value_product_attribute_value_proto protoreflect.FileDescriptor

var file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDesc = []byte{
	0x0a, 0x47, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x1f,
	0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xc2, 0x01, 0x0a, 0x20, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x68, 0x0a, 0x17, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x15, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x23, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x68, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8e, 0x01, 0x0a,
	0x22, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x68, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa3, 0x01,
	0x0a, 0x1c, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x1d, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x71, 0x0a,
	0x1c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x19, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x62, 0x0a, 0x1f, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x19, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x20, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8a,
	0x01, 0x0a, 0x1e, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x68, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x1f,
	0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x34, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x68, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32,
	0x93, 0x06, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x12, 0x95, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x49, 0x6e, 0x5f, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x39, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x9e, 0x01, 0x0a, 0x1f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3c, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x8c, 0x01, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x36,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x00, 0x12, 0x95, 0x01, 0x0a, 0x1c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x1a, 0x39, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x75,
	0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x92, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x49, 0x6e, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x00, 0x42, 0x78, 0x0a, 0x33, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x69, 0x61,
	0x6e, 0x78, 0x75, 0x6e, 0x6b, 0x65, 0x2e, 0x65, 0x67, 0x6f, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x15, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74, 0x2f, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescOnce sync.Once
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescData = file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDesc
)

func file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescGZIP() []byte {
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescOnce.Do(func() {
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescData)
	})
	return file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDescData
}

var file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_modules_inventory_product_attribute_value_product_attribute_value_proto_goTypes = []interface{}{
	(*ProductAttributeValue)(nil),               // 0: product_attribute_value.Product_attribute_value
	(*Error)(nil),                               // 1: product_attribute_value.Error
	(*In_GetProductAttributeValueById)(nil),     // 2: product_attribute_value.In_GetProductAttributeValueById
	(*Out_GetProductAttributeValueById)(nil),    // 3: product_attribute_value.Out_GetProductAttributeValueById
	(*Out_UpdateProductAttributeValueInfo)(nil), // 4: product_attribute_value.Out_UpdateProductAttributeValueInfo
	(*In_UpdateProductAttributeValueInfo)(nil),  // 5: product_attribute_value.In_UpdateProductAttributeValueInfo
	(*In_GetProductAttributeValues)(nil),        // 6: product_attribute_value.In_GetProductAttributeValues
	(*Out_GetProductAttributeValues)(nil),       // 7: product_attribute_value.Out_GetProductAttributeValues
	(*In_DeleteProductAttributeValues)(nil),     // 8: product_attribute_value.In_DeleteProductAttributeValues
	(*Out_DeleteProductAttributeValues)(nil),    // 9: product_attribute_value.Out_DeleteProductAttributeValues
	(*In_CreateProductAttributeValue)(nil),      // 10: product_attribute_value.In_CreateProductAttributeValue
	(*Out_CreateProductAttributeValue)(nil),     // 11: product_attribute_value.Out_CreateProductAttributeValue
}
var file_modules_inventory_product_attribute_value_product_attribute_value_proto_depIdxs = []int32{
	1,  // 0: product_attribute_value.Out_GetProductAttributeValueById.error:type_name -> product_attribute_value.Error
	0,  // 1: product_attribute_value.Out_GetProductAttributeValueById.product_attribute_value:type_name -> product_attribute_value.Product_attribute_value
	1,  // 2: product_attribute_value.Out_UpdateProductAttributeValueInfo.error:type_name -> product_attribute_value.Error
	0,  // 3: product_attribute_value.Out_UpdateProductAttributeValueInfo.product_attribute_value:type_name -> product_attribute_value.Product_attribute_value
	0,  // 4: product_attribute_value.In_UpdateProductAttributeValueInfo.product_attribute_value:type_name -> product_attribute_value.Product_attribute_value
	1,  // 5: product_attribute_value.Out_GetProductAttributeValues.error:type_name -> product_attribute_value.Error
	0,  // 6: product_attribute_value.Out_GetProductAttributeValues.product_attribute_value_list:type_name -> product_attribute_value.Product_attribute_value
	1,  // 7: product_attribute_value.Out_DeleteProductAttributeValues.error:type_name -> product_attribute_value.Error
	0,  // 8: product_attribute_value.In_CreateProductAttributeValue.product_attribute_value:type_name -> product_attribute_value.Product_attribute_value
	1,  // 9: product_attribute_value.Out_CreateProductAttributeValue.error:type_name -> product_attribute_value.Error
	0,  // 10: product_attribute_value.Out_CreateProductAttributeValue.product_attribute_value:type_name -> product_attribute_value.Product_attribute_value
	2,  // 11: product_attribute_value.ProductAttributeValueHandler.GetProductAttributeValueById:input_type -> product_attribute_value.In_GetProductAttributeValueById
	5,  // 12: product_attribute_value.ProductAttributeValueHandler.UpdateProductAttributeValueInfo:input_type -> product_attribute_value.In_UpdateProductAttributeValueInfo
	6,  // 13: product_attribute_value.ProductAttributeValueHandler.GetProductAttributeValues:input_type -> product_attribute_value.In_GetProductAttributeValues
	8,  // 14: product_attribute_value.ProductAttributeValueHandler.DeleteProductAttributeValues:input_type -> product_attribute_value.In_DeleteProductAttributeValues
	10, // 15: product_attribute_value.ProductAttributeValueHandler.CreateProductAttributeValue:input_type -> product_attribute_value.In_CreateProductAttributeValue
	3,  // 16: product_attribute_value.ProductAttributeValueHandler.GetProductAttributeValueById:output_type -> product_attribute_value.Out_GetProductAttributeValueById
	4,  // 17: product_attribute_value.ProductAttributeValueHandler.UpdateProductAttributeValueInfo:output_type -> product_attribute_value.Out_UpdateProductAttributeValueInfo
	7,  // 18: product_attribute_value.ProductAttributeValueHandler.GetProductAttributeValues:output_type -> product_attribute_value.Out_GetProductAttributeValues
	9,  // 19: product_attribute_value.ProductAttributeValueHandler.DeleteProductAttributeValues:output_type -> product_attribute_value.Out_DeleteProductAttributeValues
	11, // 20: product_attribute_value.ProductAttributeValueHandler.CreateProductAttributeValue:output_type -> product_attribute_value.Out_CreateProductAttributeValue
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_modules_inventory_product_attribute_value_product_attribute_value_proto_init() }
func file_modules_inventory_product_attribute_value_product_attribute_value_proto_init() {
	if File_modules_inventory_product_attribute_value_product_attribute_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductAttributeValueById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductAttributeValueById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateProductAttributeValueInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateProductAttributeValueInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductAttributeValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductAttributeValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteProductAttributeValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteProductAttributeValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateProductAttributeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateProductAttributeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_inventory_product_attribute_value_product_attribute_value_proto_goTypes,
		DependencyIndexes: file_modules_inventory_product_attribute_value_product_attribute_value_proto_depIdxs,
		MessageInfos:      file_modules_inventory_product_attribute_value_product_attribute_value_proto_msgTypes,
	}.Build()
	File_modules_inventory_product_attribute_value_product_attribute_value_proto = out.File
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_rawDesc = nil
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_goTypes = nil
	file_modules_inventory_product_attribute_value_product_attribute_value_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductAttributeValueHandlerClient is the client API for ProductAttributeValueHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductAttributeValueHandlerClient interface {
	//获取信息
	GetProductAttributeValueById(ctx context.Context, in *In_GetProductAttributeValueById, opts ...grpc.CallOption) (*Out_GetProductAttributeValueById, error)
	//修改信息
	UpdateProductAttributeValueInfo(ctx context.Context, in *In_UpdateProductAttributeValueInfo, opts ...grpc.CallOption) (*Out_UpdateProductAttributeValueInfo, error)
	//获取列表
	GetProductAttributeValues(ctx context.Context, in *In_GetProductAttributeValues, opts ...grpc.CallOption) (*Out_GetProductAttributeValues, error)
	//删除列表
	DeleteProductAttributeValues(ctx context.Context, in *In_DeleteProductAttributeValues, opts ...grpc.CallOption) (*Out_DeleteProductAttributeValues, error)
	//新建信息
	CreateProductAttributeValue(ctx context.Context, in *In_CreateProductAttributeValue, opts ...grpc.CallOption) (*Out_CreateProductAttributeValue, error)
}

type productAttributeValueHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAttributeValueHandlerClient(cc grpc.ClientConnInterface) ProductAttributeValueHandlerClient {
	return &productAttributeValueHandlerClient{cc}
}

func (c *productAttributeValueHandlerClient) GetProductAttributeValueById(ctx context.Context, in *In_GetProductAttributeValueById, opts ...grpc.CallOption) (*Out_GetProductAttributeValueById, error) {
	out := new(Out_GetProductAttributeValueById)
	err := c.cc.Invoke(ctx, "/product_attribute_value.ProductAttributeValueHandler/GetProductAttributeValueById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAttributeValueHandlerClient) UpdateProductAttributeValueInfo(ctx context.Context, in *In_UpdateProductAttributeValueInfo, opts ...grpc.CallOption) (*Out_UpdateProductAttributeValueInfo, error) {
	out := new(Out_UpdateProductAttributeValueInfo)
	err := c.cc.Invoke(ctx, "/product_attribute_value.ProductAttributeValueHandler/UpdateProductAttributeValueInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAttributeValueHandlerClient) GetProductAttributeValues(ctx context.Context, in *In_GetProductAttributeValues, opts ...grpc.CallOption) (*Out_GetProductAttributeValues, error) {
	out := new(Out_GetProductAttributeValues)
	err := c.cc.Invoke(ctx, "/product_attribute_value.ProductAttributeValueHandler/GetProductAttributeValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAttributeValueHandlerClient) DeleteProductAttributeValues(ctx context.Context, in *In_DeleteProductAttributeValues, opts ...grpc.CallOption) (*Out_DeleteProductAttributeValues, error) {
	out := new(Out_DeleteProductAttributeValues)
	err := c.cc.Invoke(ctx, "/product_attribute_value.ProductAttributeValueHandler/DeleteProductAttributeValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAttributeValueHandlerClient) CreateProductAttributeValue(ctx context.Context, in *In_CreateProductAttributeValue, opts ...grpc.CallOption) (*Out_CreateProductAttributeValue, error) {
	out := new(Out_CreateProductAttributeValue)
	err := c.cc.Invoke(ctx, "/product_attribute_value.ProductAttributeValueHandler/CreateProductAttributeValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAttributeValueHandlerServer is the server API for ProductAttributeValueHandler service.
type ProductAttributeValueHandlerServer interface {
	//获取信息
	GetProductAttributeValueById(context.Context, *In_GetProductAttributeValueById) (*Out_GetProductAttributeValueById, error)
	//修改信息
	UpdateProductAttributeValueInfo(context.Context, *In_UpdateProductAttributeValueInfo) (*Out_UpdateProductAttributeValueInfo, error)
	//获取列表
	GetProductAttributeValues(context.Context, *In_GetProductAttributeValues) (*Out_GetProductAttributeValues, error)
	//删除列表
	DeleteProductAttributeValues(context.Context, *In_DeleteProductAttributeValues) (*Out_DeleteProductAttributeValues, error)
	//新建信息
	CreateProductAttributeValue(context.Context, *In_CreateProductAttributeValue) (*Out_CreateProductAttributeValue, error)
}

// UnimplementedProductAttributeValueHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedProductAttributeValueHandlerServer struct {
}

func (*UnimplementedProductAttributeValueHandlerServer) GetProductAttributeValueById(context.Context, *In_GetProductAttributeValueById) (*Out_GetProductAttributeValueById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductAttributeValueById not implemented")
}
func (*UnimplementedProductAttributeValueHandlerServer) UpdateProductAttributeValueInfo(context.Context, *In_UpdateProductAttributeValueInfo) (*Out_UpdateProductAttributeValueInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductAttributeValueInfo not implemented")
}
func (*UnimplementedProductAttributeValueHandlerServer) GetProductAttributeValues(context.Context, *In_GetProductAttributeValues) (*Out_GetProductAttributeValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductAttributeValues not implemented")
}
func (*UnimplementedProductAttributeValueHandlerServer) DeleteProductAttributeValues(context.Context, *In_DeleteProductAttributeValues) (*Out_DeleteProductAttributeValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductAttributeValues not implemented")
}
func (*UnimplementedProductAttributeValueHandlerServer) CreateProductAttributeValue(context.Context, *In_CreateProductAttributeValue) (*Out_CreateProductAttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductAttributeValue not implemented")
}

func RegisterProductAttributeValueHandlerServer(s *grpc.Server, srv ProductAttributeValueHandlerServer) {
	s.RegisterService(&_ProductAttributeValueHandler_serviceDesc, srv)
}

func _ProductAttributeValueHandler_GetProductAttributeValueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductAttributeValueById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAttributeValueHandlerServer).GetProductAttributeValueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_attribute_value.ProductAttributeValueHandler/GetProductAttributeValueById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAttributeValueHandlerServer).GetProductAttributeValueById(ctx, req.(*In_GetProductAttributeValueById))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAttributeValueHandler_UpdateProductAttributeValueInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateProductAttributeValueInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAttributeValueHandlerServer).UpdateProductAttributeValueInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_attribute_value.ProductAttributeValueHandler/UpdateProductAttributeValueInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAttributeValueHandlerServer).UpdateProductAttributeValueInfo(ctx, req.(*In_UpdateProductAttributeValueInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAttributeValueHandler_GetProductAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductAttributeValues)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAttributeValueHandlerServer).GetProductAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_attribute_value.ProductAttributeValueHandler/GetProductAttributeValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAttributeValueHandlerServer).GetProductAttributeValues(ctx, req.(*In_GetProductAttributeValues))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAttributeValueHandler_DeleteProductAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteProductAttributeValues)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAttributeValueHandlerServer).DeleteProductAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_attribute_value.ProductAttributeValueHandler/DeleteProductAttributeValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAttributeValueHandlerServer).DeleteProductAttributeValues(ctx, req.(*In_DeleteProductAttributeValues))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAttributeValueHandler_CreateProductAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateProductAttributeValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAttributeValueHandlerServer).CreateProductAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_attribute_value.ProductAttributeValueHandler/CreateProductAttributeValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAttributeValueHandlerServer).CreateProductAttributeValue(ctx, req.(*In_CreateProductAttributeValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductAttributeValueHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product_attribute_value.ProductAttributeValueHandler",
	HandlerType: (*ProductAttributeValueHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductAttributeValueById",
			Handler:    _ProductAttributeValueHandler_GetProductAttributeValueById_Handler,
		},
		{
			MethodName: "UpdateProductAttributeValueInfo",
			Handler:    _ProductAttributeValueHandler_UpdateProductAttributeValueInfo_Handler,
		},
		{
			MethodName: "GetProductAttributeValues",
			Handler:    _ProductAttributeValueHandler_GetProductAttributeValues_Handler,
		},
		{
			MethodName: "DeleteProductAttributeValues",
			Handler:    _ProductAttributeValueHandler_DeleteProductAttributeValues_Handler,
		},
		{
			MethodName: "CreateProductAttributeValue",
			Handler:    _ProductAttributeValueHandler_CreateProductAttributeValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/inventory/product_attribute_value/product_attribute_value.proto",
}
