// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.10.1
// source: modules/inventory/product_full_reduction/product_full_reduction.proto

package product_full_reduction

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProductFullReduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId   string  `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FullPrice   float32 `protobuf:"fixed32,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	ReducePrice int64   `protobuf:"varint,4,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,omitempty"`
}

func (x *ProductFullReduction) Reset() {
	*x = ProductFullReduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductFullReduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFullReduction) ProtoMessage() {}

func (x *ProductFullReduction) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFullReduction.ProtoReflect.Descriptor instead.
func (*ProductFullReduction) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{0}
}

func (x *ProductFullReduction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductFullReduction) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductFullReduction) GetFullPrice() float32 {
	if x != nil {
		return x.FullPrice
	}
	return 0
}

func (x *ProductFullReduction) GetReducePrice() int64 {
	if x != nil {
		return x.ReducePrice
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type In_GetProductFullReductionById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *In_GetProductFullReductionById) Reset() {
	*x = In_GetProductFullReductionById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductFullReductionById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductFullReductionById) ProtoMessage() {}

func (x *In_GetProductFullReductionById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductFullReductionById.ProtoReflect.Descriptor instead.
func (*In_GetProductFullReductionById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{2}
}

func (x *In_GetProductFullReductionById) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Out_GetProductFullReductionById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
}

func (x *Out_GetProductFullReductionById) Reset() {
	*x = Out_GetProductFullReductionById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductFullReductionById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductFullReductionById) ProtoMessage() {}

func (x *Out_GetProductFullReductionById) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductFullReductionById.ProtoReflect.Descriptor instead.
func (*Out_GetProductFullReductionById) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{3}
}

func (x *Out_GetProductFullReductionById) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductFullReductionById) GetProductFullReduction() *ProductFullReduction {
	if x != nil {
		return x.ProductFullReduction
	}
	return nil
}

type Out_UpdateProductFullReductionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
}

func (x *Out_UpdateProductFullReductionInfo) Reset() {
	*x = Out_UpdateProductFullReductionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_UpdateProductFullReductionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_UpdateProductFullReductionInfo) ProtoMessage() {}

func (x *Out_UpdateProductFullReductionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_UpdateProductFullReductionInfo.ProtoReflect.Descriptor instead.
func (*Out_UpdateProductFullReductionInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{4}
}

func (x *Out_UpdateProductFullReductionInfo) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_UpdateProductFullReductionInfo) GetProductFullReduction() *ProductFullReduction {
	if x != nil {
		return x.ProductFullReduction
	}
	return nil
}

type In_UpdateProductFullReductionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductFullReduction *ProductFullReduction `protobuf:"bytes,1,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
}

func (x *In_UpdateProductFullReductionInfo) Reset() {
	*x = In_UpdateProductFullReductionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_UpdateProductFullReductionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_UpdateProductFullReductionInfo) ProtoMessage() {}

func (x *In_UpdateProductFullReductionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_UpdateProductFullReductionInfo.ProtoReflect.Descriptor instead.
func (*In_UpdateProductFullReductionInfo) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{5}
}

func (x *In_UpdateProductFullReductionInfo) GetProductFullReduction() *ProductFullReduction {
	if x != nil {
		return x.ProductFullReduction
	}
	return nil
}

type In_GetProductFullReductions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit     int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages     int64  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey string `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime string `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *In_GetProductFullReductions) Reset() {
	*x = In_GetProductFullReductions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_GetProductFullReductions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_GetProductFullReductions) ProtoMessage() {}

func (x *In_GetProductFullReductions) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_GetProductFullReductions.ProtoReflect.Descriptor instead.
func (*In_GetProductFullReductions) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{6}
}

func (x *In_GetProductFullReductions) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *In_GetProductFullReductions) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *In_GetProductFullReductions) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *In_GetProductFullReductions) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *In_GetProductFullReductions) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Out_GetProductFullReductions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                    *Error                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                    int64                   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                    int64                   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                    int64                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductFullReductionList []*ProductFullReduction `protobuf:"bytes,5,rep,name=productFullReduction_list,json=productFullReductionList,proto3" json:"productFullReduction_list,omitempty"`
}

func (x *Out_GetProductFullReductions) Reset() {
	*x = Out_GetProductFullReductions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_GetProductFullReductions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_GetProductFullReductions) ProtoMessage() {}

func (x *Out_GetProductFullReductions) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_GetProductFullReductions.ProtoReflect.Descriptor instead.
func (*Out_GetProductFullReductions) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{7}
}

func (x *Out_GetProductFullReductions) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_GetProductFullReductions) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Out_GetProductFullReductions) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Out_GetProductFullReductions) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Out_GetProductFullReductions) GetProductFullReductionList() []*ProductFullReduction {
	if x != nil {
		return x.ProductFullReductionList
	}
	return nil
}

type In_DeleteProductFullReductions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductFullReductionList []int64 `protobuf:"varint,1,rep,packed,name=ProductFullReduction_list,json=ProductFullReductionList,proto3" json:"ProductFullReduction_list,omitempty"`
}

func (x *In_DeleteProductFullReductions) Reset() {
	*x = In_DeleteProductFullReductions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_DeleteProductFullReductions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_DeleteProductFullReductions) ProtoMessage() {}

func (x *In_DeleteProductFullReductions) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_DeleteProductFullReductions.ProtoReflect.Descriptor instead.
func (*In_DeleteProductFullReductions) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{8}
}

func (x *In_DeleteProductFullReductions) GetProductFullReductionList() []int64 {
	if x != nil {
		return x.ProductFullReductionList
	}
	return nil
}

type Out_DeleteProductFullReductions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Out_DeleteProductFullReductions) Reset() {
	*x = Out_DeleteProductFullReductions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_DeleteProductFullReductions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_DeleteProductFullReductions) ProtoMessage() {}

func (x *Out_DeleteProductFullReductions) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_DeleteProductFullReductions.ProtoReflect.Descriptor instead.
func (*Out_DeleteProductFullReductions) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{9}
}

func (x *Out_DeleteProductFullReductions) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type In_CreateProductFullReduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductFullReduction *ProductFullReduction `protobuf:"bytes,1,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
}

func (x *In_CreateProductFullReduction) Reset() {
	*x = In_CreateProductFullReduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In_CreateProductFullReduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In_CreateProductFullReduction) ProtoMessage() {}

func (x *In_CreateProductFullReduction) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In_CreateProductFullReduction.ProtoReflect.Descriptor instead.
func (*In_CreateProductFullReduction) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{10}
}

func (x *In_CreateProductFullReduction) GetProductFullReduction() *ProductFullReduction {
	if x != nil {
		return x.ProductFullReduction
	}
	return nil
}

type Out_CreateProductFullReduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
}

func (x *Out_CreateProductFullReduction) Reset() {
	*x = Out_CreateProductFullReduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out_CreateProductFullReduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out_CreateProductFullReduction) ProtoMessage() {}

func (x *Out_CreateProductFullReduction) ProtoReflect() protoreflect.Message {
	mi := &file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out_CreateProductFullReduction.ProtoReflect.Descriptor instead.
func (*Out_CreateProductFullReduction) Descriptor() ([]byte, []int) {
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP(), []int{11}
}

func (x *Out_CreateProductFullReduction) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Out_CreateProductFullReduction) GetProductFullReduction() *ProductFullReduction {
	if x != nil {
		return x.ProductFullReduction
	}
	return nil
}

var File_modules_inventory_product_full_reduction_product_full_reduction_proto protoreflect.FileDescriptor

var file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDesc = []byte{
	0x0a, 0x45, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c,
	0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x89, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c,
	0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x66,
	0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x30, 0x0a, 0x1e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xba, 0x01, 0x0a, 0x1f, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x62, 0x0a,
	0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xbd, 0x01, 0x0a, 0x22, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x62, 0x0a,
	0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x87, 0x01, 0x0a, 0x21, 0x49, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x62, 0x0a, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x1b,
	0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x82, 0x02, 0x0a, 0x1c, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x6b, 0x0a, 0x19, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x1e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x18, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x1f, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x83, 0x01, 0x0a,
	0x1d, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x62,
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75,
	0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xb9, 0x01, 0x0a, 0x1e, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x62, 0x0a, 0x14, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xf9,
	0x05, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x90,
	0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x36,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x22,
	0x00, 0x12, 0x99, 0x01, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e,
	0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x3a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x87, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x34, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x12, 0x90, 0x01, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x37, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x12, 0x8d, 0x01, 0x0a, 0x1a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x75, 0x0a, 0x32, 0x63, 0x6f,
	0x6d, 0x2e, 0x71, 0x69, 0x61, 0x6e, 0x78, 0x75, 0x6e, 0x6b, 0x65, 0x2e, 0x65, 0x67, 0x6f, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x14, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x6f, 0x5f, 0x6f, 0x75, 0x74,
	0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescOnce sync.Once
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescData = file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDesc
)

func file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescGZIP() []byte {
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescOnce.Do(func() {
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescData)
	})
	return file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDescData
}

var file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_modules_inventory_product_full_reduction_product_full_reduction_proto_goTypes = []interface{}{
	(*ProductFullReduction)(nil),               // 0: product_full_reduction.Product_full_reduction
	(*Error)(nil),                              // 1: product_full_reduction.Error
	(*In_GetProductFullReductionById)(nil),     // 2: product_full_reduction.In_GetProductFullReductionById
	(*Out_GetProductFullReductionById)(nil),    // 3: product_full_reduction.Out_GetProductFullReductionById
	(*Out_UpdateProductFullReductionInfo)(nil), // 4: product_full_reduction.Out_UpdateProductFullReductionInfo
	(*In_UpdateProductFullReductionInfo)(nil),  // 5: product_full_reduction.In_UpdateProductFullReductionInfo
	(*In_GetProductFullReductions)(nil),        // 6: product_full_reduction.In_GetProductFullReductions
	(*Out_GetProductFullReductions)(nil),       // 7: product_full_reduction.Out_GetProductFullReductions
	(*In_DeleteProductFullReductions)(nil),     // 8: product_full_reduction.In_DeleteProductFullReductions
	(*Out_DeleteProductFullReductions)(nil),    // 9: product_full_reduction.Out_DeleteProductFullReductions
	(*In_CreateProductFullReduction)(nil),      // 10: product_full_reduction.In_CreateProductFullReduction
	(*Out_CreateProductFullReduction)(nil),     // 11: product_full_reduction.Out_CreateProductFullReduction
}
var file_modules_inventory_product_full_reduction_product_full_reduction_proto_depIdxs = []int32{
	1,  // 0: product_full_reduction.Out_GetProductFullReductionById.error:type_name -> product_full_reduction.Error
	0,  // 1: product_full_reduction.Out_GetProductFullReductionById.productFullReduction:type_name -> product_full_reduction.Product_full_reduction
	1,  // 2: product_full_reduction.Out_UpdateProductFullReductionInfo.error:type_name -> product_full_reduction.Error
	0,  // 3: product_full_reduction.Out_UpdateProductFullReductionInfo.productFullReduction:type_name -> product_full_reduction.Product_full_reduction
	0,  // 4: product_full_reduction.In_UpdateProductFullReductionInfo.productFullReduction:type_name -> product_full_reduction.Product_full_reduction
	1,  // 5: product_full_reduction.Out_GetProductFullReductions.error:type_name -> product_full_reduction.Error
	0,  // 6: product_full_reduction.Out_GetProductFullReductions.productFullReduction_list:type_name -> product_full_reduction.Product_full_reduction
	1,  // 7: product_full_reduction.Out_DeleteProductFullReductions.error:type_name -> product_full_reduction.Error
	0,  // 8: product_full_reduction.In_CreateProductFullReduction.productFullReduction:type_name -> product_full_reduction.Product_full_reduction
	1,  // 9: product_full_reduction.Out_CreateProductFullReduction.error:type_name -> product_full_reduction.Error
	0,  // 10: product_full_reduction.Out_CreateProductFullReduction.productFullReduction:type_name -> product_full_reduction.Product_full_reduction
	2,  // 11: product_full_reduction.ProductFullReductionHandler.GetProductFullReductionById:input_type -> product_full_reduction.In_GetProductFullReductionById
	5,  // 12: product_full_reduction.ProductFullReductionHandler.UpdateProductFullReductionInfo:input_type -> product_full_reduction.In_UpdateProductFullReductionInfo
	6,  // 13: product_full_reduction.ProductFullReductionHandler.GetProductFullReductions:input_type -> product_full_reduction.In_GetProductFullReductions
	8,  // 14: product_full_reduction.ProductFullReductionHandler.DeleteProductFullReductions:input_type -> product_full_reduction.In_DeleteProductFullReductions
	10, // 15: product_full_reduction.ProductFullReductionHandler.CreateProductFullReduction:input_type -> product_full_reduction.In_CreateProductFullReduction
	3,  // 16: product_full_reduction.ProductFullReductionHandler.GetProductFullReductionById:output_type -> product_full_reduction.Out_GetProductFullReductionById
	4,  // 17: product_full_reduction.ProductFullReductionHandler.UpdateProductFullReductionInfo:output_type -> product_full_reduction.Out_UpdateProductFullReductionInfo
	7,  // 18: product_full_reduction.ProductFullReductionHandler.GetProductFullReductions:output_type -> product_full_reduction.Out_GetProductFullReductions
	9,  // 19: product_full_reduction.ProductFullReductionHandler.DeleteProductFullReductions:output_type -> product_full_reduction.Out_DeleteProductFullReductions
	11, // 20: product_full_reduction.ProductFullReductionHandler.CreateProductFullReduction:output_type -> product_full_reduction.Out_CreateProductFullReduction
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_modules_inventory_product_full_reduction_product_full_reduction_proto_init() }
func file_modules_inventory_product_full_reduction_product_full_reduction_proto_init() {
	if File_modules_inventory_product_full_reduction_product_full_reduction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductFullReduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductFullReductionById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductFullReductionById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_UpdateProductFullReductionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_UpdateProductFullReductionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_GetProductFullReductions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_GetProductFullReductions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_DeleteProductFullReductions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_DeleteProductFullReductions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In_CreateProductFullReduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out_CreateProductFullReduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_inventory_product_full_reduction_product_full_reduction_proto_goTypes,
		DependencyIndexes: file_modules_inventory_product_full_reduction_product_full_reduction_proto_depIdxs,
		MessageInfos:      file_modules_inventory_product_full_reduction_product_full_reduction_proto_msgTypes,
	}.Build()
	File_modules_inventory_product_full_reduction_product_full_reduction_proto = out.File
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_rawDesc = nil
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_goTypes = nil
	file_modules_inventory_product_full_reduction_product_full_reduction_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductFullReductionHandlerClient is the client API for ProductFullReductionHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductFullReductionHandlerClient interface {
	//获取信息
	GetProductFullReductionById(ctx context.Context, in *In_GetProductFullReductionById, opts ...grpc.CallOption) (*Out_GetProductFullReductionById, error)
	//修改信息
	UpdateProductFullReductionInfo(ctx context.Context, in *In_UpdateProductFullReductionInfo, opts ...grpc.CallOption) (*Out_UpdateProductFullReductionInfo, error)
	//获取列表
	GetProductFullReductions(ctx context.Context, in *In_GetProductFullReductions, opts ...grpc.CallOption) (*Out_GetProductFullReductions, error)
	//删除列表
	DeleteProductFullReductions(ctx context.Context, in *In_DeleteProductFullReductions, opts ...grpc.CallOption) (*Out_DeleteProductFullReductions, error)
	//新建信息
	CreateProductFullReduction(ctx context.Context, in *In_CreateProductFullReduction, opts ...grpc.CallOption) (*Out_CreateProductFullReduction, error)
}

type productFullReductionHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewProductFullReductionHandlerClient(cc grpc.ClientConnInterface) ProductFullReductionHandlerClient {
	return &productFullReductionHandlerClient{cc}
}

func (c *productFullReductionHandlerClient) GetProductFullReductionById(ctx context.Context, in *In_GetProductFullReductionById, opts ...grpc.CallOption) (*Out_GetProductFullReductionById, error) {
	out := new(Out_GetProductFullReductionById)
	err := c.cc.Invoke(ctx, "/product_full_reduction.ProductFullReductionHandler/GetProductFullReductionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFullReductionHandlerClient) UpdateProductFullReductionInfo(ctx context.Context, in *In_UpdateProductFullReductionInfo, opts ...grpc.CallOption) (*Out_UpdateProductFullReductionInfo, error) {
	out := new(Out_UpdateProductFullReductionInfo)
	err := c.cc.Invoke(ctx, "/product_full_reduction.ProductFullReductionHandler/UpdateProductFullReductionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFullReductionHandlerClient) GetProductFullReductions(ctx context.Context, in *In_GetProductFullReductions, opts ...grpc.CallOption) (*Out_GetProductFullReductions, error) {
	out := new(Out_GetProductFullReductions)
	err := c.cc.Invoke(ctx, "/product_full_reduction.ProductFullReductionHandler/GetProductFullReductions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFullReductionHandlerClient) DeleteProductFullReductions(ctx context.Context, in *In_DeleteProductFullReductions, opts ...grpc.CallOption) (*Out_DeleteProductFullReductions, error) {
	out := new(Out_DeleteProductFullReductions)
	err := c.cc.Invoke(ctx, "/product_full_reduction.ProductFullReductionHandler/DeleteProductFullReductions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFullReductionHandlerClient) CreateProductFullReduction(ctx context.Context, in *In_CreateProductFullReduction, opts ...grpc.CallOption) (*Out_CreateProductFullReduction, error) {
	out := new(Out_CreateProductFullReduction)
	err := c.cc.Invoke(ctx, "/product_full_reduction.ProductFullReductionHandler/CreateProductFullReduction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductFullReductionHandlerServer is the server API for ProductFullReductionHandler service.
type ProductFullReductionHandlerServer interface {
	//获取信息
	GetProductFullReductionById(context.Context, *In_GetProductFullReductionById) (*Out_GetProductFullReductionById, error)
	//修改信息
	UpdateProductFullReductionInfo(context.Context, *In_UpdateProductFullReductionInfo) (*Out_UpdateProductFullReductionInfo, error)
	//获取列表
	GetProductFullReductions(context.Context, *In_GetProductFullReductions) (*Out_GetProductFullReductions, error)
	//删除列表
	DeleteProductFullReductions(context.Context, *In_DeleteProductFullReductions) (*Out_DeleteProductFullReductions, error)
	//新建信息
	CreateProductFullReduction(context.Context, *In_CreateProductFullReduction) (*Out_CreateProductFullReduction, error)
}

// UnimplementedProductFullReductionHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedProductFullReductionHandlerServer struct {
}

func (*UnimplementedProductFullReductionHandlerServer) GetProductFullReductionById(context.Context, *In_GetProductFullReductionById) (*Out_GetProductFullReductionById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductFullReductionById not implemented")
}
func (*UnimplementedProductFullReductionHandlerServer) UpdateProductFullReductionInfo(context.Context, *In_UpdateProductFullReductionInfo) (*Out_UpdateProductFullReductionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductFullReductionInfo not implemented")
}
func (*UnimplementedProductFullReductionHandlerServer) GetProductFullReductions(context.Context, *In_GetProductFullReductions) (*Out_GetProductFullReductions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductFullReductions not implemented")
}
func (*UnimplementedProductFullReductionHandlerServer) DeleteProductFullReductions(context.Context, *In_DeleteProductFullReductions) (*Out_DeleteProductFullReductions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductFullReductions not implemented")
}
func (*UnimplementedProductFullReductionHandlerServer) CreateProductFullReduction(context.Context, *In_CreateProductFullReduction) (*Out_CreateProductFullReduction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductFullReduction not implemented")
}

func RegisterProductFullReductionHandlerServer(s *grpc.Server, srv ProductFullReductionHandlerServer) {
	s.RegisterService(&_ProductFullReductionHandler_serviceDesc, srv)
}

func _ProductFullReductionHandler_GetProductFullReductionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductFullReductionById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFullReductionHandlerServer).GetProductFullReductionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_full_reduction.ProductFullReductionHandler/GetProductFullReductionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFullReductionHandlerServer).GetProductFullReductionById(ctx, req.(*In_GetProductFullReductionById))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFullReductionHandler_UpdateProductFullReductionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_UpdateProductFullReductionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFullReductionHandlerServer).UpdateProductFullReductionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_full_reduction.ProductFullReductionHandler/UpdateProductFullReductionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFullReductionHandlerServer).UpdateProductFullReductionInfo(ctx, req.(*In_UpdateProductFullReductionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFullReductionHandler_GetProductFullReductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_GetProductFullReductions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFullReductionHandlerServer).GetProductFullReductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_full_reduction.ProductFullReductionHandler/GetProductFullReductions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFullReductionHandlerServer).GetProductFullReductions(ctx, req.(*In_GetProductFullReductions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFullReductionHandler_DeleteProductFullReductions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_DeleteProductFullReductions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFullReductionHandlerServer).DeleteProductFullReductions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_full_reduction.ProductFullReductionHandler/DeleteProductFullReductions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFullReductionHandlerServer).DeleteProductFullReductions(ctx, req.(*In_DeleteProductFullReductions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFullReductionHandler_CreateProductFullReduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(In_CreateProductFullReduction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFullReductionHandlerServer).CreateProductFullReduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_full_reduction.ProductFullReductionHandler/CreateProductFullReduction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFullReductionHandlerServer).CreateProductFullReduction(ctx, req.(*In_CreateProductFullReduction))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductFullReductionHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product_full_reduction.ProductFullReductionHandler",
	HandlerType: (*ProductFullReductionHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductFullReductionById",
			Handler:    _ProductFullReductionHandler_GetProductFullReductionById_Handler,
		},
		{
			MethodName: "UpdateProductFullReductionInfo",
			Handler:    _ProductFullReductionHandler_UpdateProductFullReductionInfo_Handler,
		},
		{
			MethodName: "GetProductFullReductions",
			Handler:    _ProductFullReductionHandler_GetProductFullReductions_Handler,
		},
		{
			MethodName: "DeleteProductFullReductions",
			Handler:    _ProductFullReductionHandler_DeleteProductFullReductions_Handler,
		},
		{
			MethodName: "CreateProductFullReduction",
			Handler:    _ProductFullReductionHandler_CreateProductFullReduction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/inventory/product_full_reduction/product_full_reduction.proto",
}
